//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Aabad 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("aabad")]
	[Serializable]
	public partial class Aabad : Entity 
	{
		#region Model
		private string _Stdcode;
		private string _StdName;
		private int? _Mainbad;
		private int? _AllBad;
		private int? _GetXF;
		/// <summary>
		/// 
		/// </summary>
		public string Stdcode
		{
			get{ return _Stdcode; }
			set
			{
				this.OnPropertyValueChange(_.Stdcode,_Stdcode,value);
				this._Stdcode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdName
		{
			get{ return _StdName; }
			set
			{
				this.OnPropertyValueChange(_.StdName,_StdName,value);
				this._StdName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Mainbad
		{
			get{ return _Mainbad; }
			set
			{
				this.OnPropertyValueChange(_.Mainbad,_Mainbad,value);
				this._Mainbad=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AllBad
		{
			get{ return _AllBad; }
			set
			{
				this.OnPropertyValueChange(_.AllBad,_AllBad,value);
				this._AllBad=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GetXF
		{
			get{ return _GetXF; }
			set
			{
				this.OnPropertyValueChange(_.GetXF,_GetXF,value);
				this._GetXF=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Stdcode,
				_.StdName,
				_.Mainbad,
				_.AllBad,
				_.GetXF};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Stdcode,
				this._StdName,
				this._Mainbad,
				this._AllBad,
				this._GetXF};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","aabad");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdcode = new Field("Stdcode","aabad","Stdcode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdName = new Field("StdName","aabad","StdName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Mainbad = new Field("Mainbad","aabad","Mainbad");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllBad = new Field("AllBad","aabad","AllBad");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GetXF = new Field("GetXF","aabad","GetXF");
		}
		#endregion


	}
}

