//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Again 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Again")]
	[Serializable]
	public partial class Again : Entity 
	{
		#region Model
		private int? _SSRID;
		private int? _SRID;
		private int? _Atyid;
		private int? _Stuid;
		private int? _CCID;
		private int? _TruePoint;
		private int? _State;
		/// <summary>
		/// 
		/// </summary>
		public int? SSRID
		{
			get{ return _SSRID; }
			set
			{
				this.OnPropertyValueChange(_.SSRID,_SSRID,value);
				this._SSRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SRID
		{
			get{ return _SRID; }
			set
			{
				this.OnPropertyValueChange(_.SRID,_SRID,value);
				this._SRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Atyid
		{
			get{ return _Atyid; }
			set
			{
				this.OnPropertyValueChange(_.Atyid,_Atyid,value);
				this._Atyid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stuid
		{
			get{ return _Stuid; }
			set
			{
				this.OnPropertyValueChange(_.Stuid,_Stuid,value);
				this._Stuid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TruePoint
		{
			get{ return _TruePoint; }
			set
			{
				this.OnPropertyValueChange(_.TruePoint,_TruePoint,value);
				this._TruePoint=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SSRID,
				_.SRID,
				_.Atyid,
				_.Stuid,
				_.CCID,
				_.TruePoint,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SSRID,
				this._SRID,
				this._Atyid,
				this._Stuid,
				this._CCID,
				this._TruePoint,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Again");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SSRID = new Field("SSRID","Again","SSRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SRID = new Field("SRID","Again","SRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atyid = new Field("Atyid","Again","Atyid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stuid = new Field("Stuid","Again","Stuid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","Again","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TruePoint = new Field("TruePoint","Again","TruePoint");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","Again","state");
		}
		#endregion


	}
}

