//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类AppraiseIdea 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("AppraiseIdea")]
	[Serializable]
	public partial class AppraiseIdea : Entity 
	{
		#region Model
		private int _APIID;
		private int? _SubjID;
		private int? _Bodid;
		private int? _TCID;
		private int? _CCID;
		private int? _PSID;
		private int? _STDID;
		private int? _APSID;
		private int? _SRID;
		private int? _ATYID;
		private string _APIContent;
		private DateTime? _APIDate;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int APIID
		{
			get{ return _APIID; }
			set
			{
				this.OnPropertyValueChange(_.APIID,_APIID,value);
				this._APIID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SubjID
		{
			get{ return _SubjID; }
			set
			{
				this.OnPropertyValueChange(_.SubjID,_SubjID,value);
				this._SubjID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Bodid
		{
			get{ return _Bodid; }
			set
			{
				this.OnPropertyValueChange(_.Bodid,_Bodid,value);
				this._Bodid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TCID
		{
			get{ return _TCID; }
			set
			{
				this.OnPropertyValueChange(_.TCID,_TCID,value);
				this._TCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? STDID
		{
			get{ return _STDID; }
			set
			{
				this.OnPropertyValueChange(_.STDID,_STDID,value);
				this._STDID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? APSID
		{
			get{ return _APSID; }
			set
			{
				this.OnPropertyValueChange(_.APSID,_APSID,value);
				this._APSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SRID
		{
			get{ return _SRID; }
			set
			{
				this.OnPropertyValueChange(_.SRID,_SRID,value);
				this._SRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATYID
		{
			get{ return _ATYID; }
			set
			{
				this.OnPropertyValueChange(_.ATYID,_ATYID,value);
				this._ATYID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string APIContent
		{
			get{ return _APIContent; }
			set
			{
				this.OnPropertyValueChange(_.APIContent,_APIContent,value);
				this._APIContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? APIDate
		{
			get{ return _APIDate; }
			set
			{
				this.OnPropertyValueChange(_.APIDate,_APIDate,value);
				this._APIDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.APIID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.APIID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.APIID,
				_.SubjID,
				_.Bodid,
				_.TCID,
				_.CCID,
				_.PSID,
				_.STDID,
				_.APSID,
				_.SRID,
				_.ATYID,
				_.APIContent,
				_.APIDate,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._APIID,
				this._SubjID,
				this._Bodid,
				this._TCID,
				this._CCID,
				this._PSID,
				this._STDID,
				this._APSID,
				this._SRID,
				this._ATYID,
				this._APIContent,
				this._APIDate,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","AppraiseIdea");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APIID = new Field("APIID","AppraiseIdea","APIID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjID = new Field("SubjID","AppraiseIdea","SubjID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Bodid = new Field("Bodid","AppraiseIdea","Bodid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TCID = new Field("TCID","AppraiseIdea","TCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","AppraiseIdea","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","AppraiseIdea","PSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STDID = new Field("STDID","AppraiseIdea","STDID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APSID = new Field("APSID","AppraiseIdea","APSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SRID = new Field("SRID","AppraiseIdea","SRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATYID = new Field("ATYID","AppraiseIdea","ATYID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APIContent = new Field("APIContent","AppraiseIdea","APIContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APIDate = new Field("APIDate","AppraiseIdea","APIDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","AppraiseIdea","state");
		}
		#endregion


	}
}

