//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Chapter 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Chapter")]
	[Serializable]
	public partial class Chapter : Entity 
	{
		#region Model
		private int _ChpID;
		private int? _CCID;
		private string _ChpNo;
		private string _ChpName;
		private string _ChpRelative;
		private string _ChpDegree;
		private string _Relativechp;
		private string _LookTime;
		/// <summary>
		/// 
		/// </summary>
		public int ChpID
		{
			get{ return _ChpID; }
			set
			{
				this.OnPropertyValueChange(_.ChpID,_ChpID,value);
				this._ChpID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpNo
		{
			get{ return _ChpNo; }
			set
			{
				this.OnPropertyValueChange(_.ChpNo,_ChpNo,value);
				this._ChpNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpName
		{
			get{ return _ChpName; }
			set
			{
				this.OnPropertyValueChange(_.ChpName,_ChpName,value);
				this._ChpName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpRelative
		{
			get{ return _ChpRelative; }
			set
			{
				this.OnPropertyValueChange(_.ChpRelative,_ChpRelative,value);
				this._ChpRelative=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpDegree
		{
			get{ return _ChpDegree; }
			set
			{
				this.OnPropertyValueChange(_.ChpDegree,_ChpDegree,value);
				this._ChpDegree=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Relativechp
		{
			get{ return _Relativechp; }
			set
			{
				this.OnPropertyValueChange(_.Relativechp,_Relativechp,value);
				this._Relativechp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LookTime
		{
			get{ return _LookTime; }
			set
			{
				this.OnPropertyValueChange(_.LookTime,_LookTime,value);
				this._LookTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ChpID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ChpID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ChpID,
				_.CCID,
				_.ChpNo,
				_.ChpName,
				_.ChpRelative,
				_.ChpDegree,
				_.Relativechp,
				_.LookTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ChpID,
				this._CCID,
				this._ChpNo,
				this._ChpName,
				this._ChpRelative,
				this._ChpDegree,
				this._Relativechp,
				this._LookTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Chapter");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpID = new Field("ChpID","Chapter","ChpID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","Chapter","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpNo = new Field("ChpNo","Chapter","ChpNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpName = new Field("ChpName","Chapter","ChpName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpRelative = new Field("ChpRelative","Chapter","ChpRelative");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpDegree = new Field("ChpDegree","Chapter","ChpDegree");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Relativechp = new Field("Relativechp","Chapter","Relativechp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LookTime = new Field("LookTime","Chapter","LookTime");
		}
		#endregion


	}
}

