//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ChatMRecord 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ChatMRecord")]
	[Serializable]
	public partial class ChatMRecord : Entity 
	{
		#region Model
		private int _CMRID;
		private int? _CMID;
		private int? _CRID;
		private DateTime? _CMRDate;
		private string _Operation;
		/// <summary>
		/// 
		/// </summary>
		public int CMRID
		{
			get{ return _CMRID; }
			set
			{
				this.OnPropertyValueChange(_.CMRID,_CMRID,value);
				this._CMRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CMID
		{
			get{ return _CMID; }
			set
			{
				this.OnPropertyValueChange(_.CMID,_CMID,value);
				this._CMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CRID
		{
			get{ return _CRID; }
			set
			{
				this.OnPropertyValueChange(_.CRID,_CRID,value);
				this._CRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CMRDate
		{
			get{ return _CMRDate; }
			set
			{
				this.OnPropertyValueChange(_.CMRDate,_CMRDate,value);
				this._CMRDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Operation
		{
			get{ return _Operation; }
			set
			{
				this.OnPropertyValueChange(_.Operation,_Operation,value);
				this._Operation=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.CMRID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.CMRID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CMRID,
				_.CMID,
				_.CRID,
				_.CMRDate,
				_.Operation};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CMRID,
				this._CMID,
				this._CRID,
				this._CMRDate,
				this._Operation};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ChatMRecord");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMRID = new Field("CMRID","ChatMRecord","CMRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMID = new Field("CMID","ChatMRecord","CMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRID = new Field("CRID","ChatMRecord","CRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMRDate = new Field("CMRDate","ChatMRecord","CMRDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Operation = new Field("Operation","ChatMRecord","Operation");
		}
		#endregion


	}
}

