//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类CLRSortReplace 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("CLRSortReplace")]
	[Serializable]
	public partial class CLRSortReplace : Entity 
	{
		#region Model
		private int _CLRRID;
		private string _CLRSortA;
		private string _CLRSortB;
		/// <summary>
		/// 
		/// </summary>
		public int CLRRID
		{
			get{ return _CLRRID; }
			set
			{
				this.OnPropertyValueChange(_.CLRRID,_CLRRID,value);
				this._CLRRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CLRSortA
		{
			get{ return _CLRSortA; }
			set
			{
				this.OnPropertyValueChange(_.CLRSortA,_CLRSortA,value);
				this._CLRSortA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CLRSortB
		{
			get{ return _CLRSortB; }
			set
			{
				this.OnPropertyValueChange(_.CLRSortB,_CLRSortB,value);
				this._CLRSortB=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.CLRRID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.CLRRID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CLRRID,
				_.CLRSortA,
				_.CLRSortB};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CLRRID,
				this._CLRSortA,
				this._CLRSortB};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CLRSortReplace");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLRRID = new Field("CLRRID","CLRSortReplace","CLRRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLRSortA = new Field("CLRSortA","CLRSortReplace","CLRSortA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLRSortB = new Field("CLRSortB","CLRSortReplace","CLRSortB");
		}
		#endregion


	}
}

