//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类D99_REG 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("D99_REG")]
	[Serializable]
	public partial class D99_REG : Entity 
	{
		#region Model
		private int? _ID;
		private string _Data;
		/// <summary>
		/// 
		/// </summary>
		public int? ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Data
		{
			get{ return _Data; }
			set
			{
				this.OnPropertyValueChange(_.Data,_Data,value);
				this._Data=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Data};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Data};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","D99_REG");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","D99_REG","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Data = new Field("Data","D99_REG","Data");
		}
		#endregion


	}
}

