//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类EduPlanM 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("EduPlanM")]
	[Serializable]
	public partial class EduPlanM : Entity 
	{
		#region Model
		private int _EMID;
		private string _EPName;
		private string _Version;
		private int? _GRID;
		private int? _SPID;
		private string _PYMB;
		private string _JBYQ;
		private string _JXGGSL;
		private string _ZYFX;
		private string _ZGXK;
		private string _ZYKC;
		private short? _State;
		private string _XState;
		private string _XZXW;
		private string _SSYD1;
		private string _SSYD2;
		private string _SSYD3;
		private string _SSYD4;
		/// <summary>
		/// 
		/// </summary>
		public int EMID
		{
			get{ return _EMID; }
			set
			{
				this.OnPropertyValueChange(_.EMID,_EMID,value);
				this._EMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string EPName
		{
			get{ return _EPName; }
			set
			{
				this.OnPropertyValueChange(_.EPName,_EPName,value);
				this._EPName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Version
		{
			get{ return _Version; }
			set
			{
				this.OnPropertyValueChange(_.Version,_Version,value);
				this._Version=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GRID
		{
			get{ return _GRID; }
			set
			{
				this.OnPropertyValueChange(_.GRID,_GRID,value);
				this._GRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SPID
		{
			get{ return _SPID; }
			set
			{
				this.OnPropertyValueChange(_.SPID,_SPID,value);
				this._SPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PYMB
		{
			get{ return _PYMB; }
			set
			{
				this.OnPropertyValueChange(_.PYMB,_PYMB,value);
				this._PYMB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string JBYQ
		{
			get{ return _JBYQ; }
			set
			{
				this.OnPropertyValueChange(_.JBYQ,_JBYQ,value);
				this._JBYQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string JXGGSL
		{
			get{ return _JXGGSL; }
			set
			{
				this.OnPropertyValueChange(_.JXGGSL,_JXGGSL,value);
				this._JXGGSL=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ZYFX
		{
			get{ return _ZYFX; }
			set
			{
				this.OnPropertyValueChange(_.ZYFX,_ZYFX,value);
				this._ZYFX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ZGXK
		{
			get{ return _ZGXK; }
			set
			{
				this.OnPropertyValueChange(_.ZGXK,_ZGXK,value);
				this._ZGXK=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ZYKC
		{
			get{ return _ZYKC; }
			set
			{
				this.OnPropertyValueChange(_.ZYKC,_ZYKC,value);
				this._ZYKC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public short? State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string XState
		{
			get{ return _XState; }
			set
			{
				this.OnPropertyValueChange(_.XState,_XState,value);
				this._XState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string XZXW
		{
			get{ return _XZXW; }
			set
			{
				this.OnPropertyValueChange(_.XZXW,_XZXW,value);
				this._XZXW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SSYD1
		{
			get{ return _SSYD1; }
			set
			{
				this.OnPropertyValueChange(_.SSYD1,_SSYD1,value);
				this._SSYD1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SSYD2
		{
			get{ return _SSYD2; }
			set
			{
				this.OnPropertyValueChange(_.SSYD2,_SSYD2,value);
				this._SSYD2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SSYD3
		{
			get{ return _SSYD3; }
			set
			{
				this.OnPropertyValueChange(_.SSYD3,_SSYD3,value);
				this._SSYD3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SSYD4
		{
			get{ return _SSYD4; }
			set
			{
				this.OnPropertyValueChange(_.SSYD4,_SSYD4,value);
				this._SSYD4=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.EMID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.EMID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.EMID,
				_.EPName,
				_.Version,
				_.GRID,
				_.SPID,
				_.PYMB,
				_.JBYQ,
				_.JXGGSL,
				_.ZYFX,
				_.ZGXK,
				_.ZYKC,
				_.State,
				_.XState,
				_.XZXW,
				_.SSYD1,
				_.SSYD2,
				_.SSYD3,
				_.SSYD4};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._EMID,
				this._EPName,
				this._Version,
				this._GRID,
				this._SPID,
				this._PYMB,
				this._JBYQ,
				this._JXGGSL,
				this._ZYFX,
				this._ZGXK,
				this._ZYKC,
				this._State,
				this._XState,
				this._XZXW,
				this._SSYD1,
				this._SSYD2,
				this._SSYD3,
				this._SSYD4};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","EduPlanM");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EMID = new Field("EMID","EduPlanM","EMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EPName = new Field("EPName","EduPlanM","EPName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Version = new Field("Version","EduPlanM","Version");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GRID = new Field("GRID","EduPlanM","GRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPID = new Field("SPID","EduPlanM","SPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PYMB = new Field("PYMB","EduPlanM","PYMB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JBYQ = new Field("JBYQ","EduPlanM","JBYQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JXGGSL = new Field("JXGGSL","EduPlanM","JXGGSL");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZYFX = new Field("ZYFX","EduPlanM","ZYFX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZGXK = new Field("ZGXK","EduPlanM","ZGXK");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZYKC = new Field("ZYKC","EduPlanM","ZYKC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","EduPlanM","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XState = new Field("XState","EduPlanM","XState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XZXW = new Field("XZXW","EduPlanM","XZXW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SSYD1 = new Field("SSYD1","EduPlanM","SSYD1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SSYD2 = new Field("SSYD2","EduPlanM","SSYD2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SSYD3 = new Field("SSYD3","EduPlanM","SSYD3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SSYD4 = new Field("SSYD4","EduPlanM","SSYD4");
		}
		#endregion


	}
}

