//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类EduTotal 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("EduTotal")]
	[Serializable]
	public partial class EduTotal : Entity 
	{
		#region Model
		private int _ETID;
		private int? _EMID;
		private string _TRName;
		private int? _TermID;
		private decimal? _LLJX;
		private decimal? _PJXS;
		private decimal? _KS;
		private decimal? _JXSX;
		private decimal? _JXSXKW;
		private decimal? _KCSJ;
		private decimal? _KCSJKW;
		private decimal? _SCSX;
		private decimal? _SCSXKW;
		private decimal? _BYSJ;
		private decimal? _BYSJKW;
		private decimal? _JX;
		private decimal? _GYLD;
		private decimal? _GYLDKW;
		private decimal? _JD;
		private decimal? _RXJY;
		private decimal? _BYJY;
		private decimal? _BYJYKW;
		private decimal? _JQ;
		private decimal? _HJ;
		/// <summary>
		/// 
		/// </summary>
		public int ETID
		{
			get{ return _ETID; }
			set
			{
				this.OnPropertyValueChange(_.ETID,_ETID,value);
				this._ETID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? EMID
		{
			get{ return _EMID; }
			set
			{
				this.OnPropertyValueChange(_.EMID,_EMID,value);
				this._EMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRName
		{
			get{ return _TRName; }
			set
			{
				this.OnPropertyValueChange(_.TRName,_TRName,value);
				this._TRName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TermID
		{
			get{ return _TermID; }
			set
			{
				this.OnPropertyValueChange(_.TermID,_TermID,value);
				this._TermID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? LLJX
		{
			get{ return _LLJX; }
			set
			{
				this.OnPropertyValueChange(_.LLJX,_LLJX,value);
				this._LLJX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PJXS
		{
			get{ return _PJXS; }
			set
			{
				this.OnPropertyValueChange(_.PJXS,_PJXS,value);
				this._PJXS=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? KS
		{
			get{ return _KS; }
			set
			{
				this.OnPropertyValueChange(_.KS,_KS,value);
				this._KS=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? JXSX
		{
			get{ return _JXSX; }
			set
			{
				this.OnPropertyValueChange(_.JXSX,_JXSX,value);
				this._JXSX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? JXSXKW
		{
			get{ return _JXSXKW; }
			set
			{
				this.OnPropertyValueChange(_.JXSXKW,_JXSXKW,value);
				this._JXSXKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? KCSJ
		{
			get{ return _KCSJ; }
			set
			{
				this.OnPropertyValueChange(_.KCSJ,_KCSJ,value);
				this._KCSJ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? KCSJKW
		{
			get{ return _KCSJKW; }
			set
			{
				this.OnPropertyValueChange(_.KCSJKW,_KCSJKW,value);
				this._KCSJKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SCSX
		{
			get{ return _SCSX; }
			set
			{
				this.OnPropertyValueChange(_.SCSX,_SCSX,value);
				this._SCSX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SCSXKW
		{
			get{ return _SCSXKW; }
			set
			{
				this.OnPropertyValueChange(_.SCSXKW,_SCSXKW,value);
				this._SCSXKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BYSJ
		{
			get{ return _BYSJ; }
			set
			{
				this.OnPropertyValueChange(_.BYSJ,_BYSJ,value);
				this._BYSJ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BYSJKW
		{
			get{ return _BYSJKW; }
			set
			{
				this.OnPropertyValueChange(_.BYSJKW,_BYSJKW,value);
				this._BYSJKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? JX
		{
			get{ return _JX; }
			set
			{
				this.OnPropertyValueChange(_.JX,_JX,value);
				this._JX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? GYLD
		{
			get{ return _GYLD; }
			set
			{
				this.OnPropertyValueChange(_.GYLD,_GYLD,value);
				this._GYLD=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? GYLDKW
		{
			get{ return _GYLDKW; }
			set
			{
				this.OnPropertyValueChange(_.GYLDKW,_GYLDKW,value);
				this._GYLDKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? JD
		{
			get{ return _JD; }
			set
			{
				this.OnPropertyValueChange(_.JD,_JD,value);
				this._JD=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? RXJY
		{
			get{ return _RXJY; }
			set
			{
				this.OnPropertyValueChange(_.RXJY,_RXJY,value);
				this._RXJY=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BYJY
		{
			get{ return _BYJY; }
			set
			{
				this.OnPropertyValueChange(_.BYJY,_BYJY,value);
				this._BYJY=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BYJYKW
		{
			get{ return _BYJYKW; }
			set
			{
				this.OnPropertyValueChange(_.BYJYKW,_BYJYKW,value);
				this._BYJYKW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? JQ
		{
			get{ return _JQ; }
			set
			{
				this.OnPropertyValueChange(_.JQ,_JQ,value);
				this._JQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? HJ
		{
			get{ return _HJ; }
			set
			{
				this.OnPropertyValueChange(_.HJ,_HJ,value);
				this._HJ=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ETID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ETID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ETID,
				_.EMID,
				_.TRName,
				_.TermID,
				_.LLJX,
				_.PJXS,
				_.KS,
				_.JXSX,
				_.JXSXKW,
				_.KCSJ,
				_.KCSJKW,
				_.SCSX,
				_.SCSXKW,
				_.BYSJ,
				_.BYSJKW,
				_.JX,
				_.GYLD,
				_.GYLDKW,
				_.JD,
				_.RXJY,
				_.BYJY,
				_.BYJYKW,
				_.JQ,
				_.HJ};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ETID,
				this._EMID,
				this._TRName,
				this._TermID,
				this._LLJX,
				this._PJXS,
				this._KS,
				this._JXSX,
				this._JXSXKW,
				this._KCSJ,
				this._KCSJKW,
				this._SCSX,
				this._SCSXKW,
				this._BYSJ,
				this._BYSJKW,
				this._JX,
				this._GYLD,
				this._GYLDKW,
				this._JD,
				this._RXJY,
				this._BYJY,
				this._BYJYKW,
				this._JQ,
				this._HJ};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","EduTotal");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ETID = new Field("ETID","EduTotal","ETID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EMID = new Field("EMID","EduTotal","EMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRName = new Field("TRName","EduTotal","TRName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TermID = new Field("TermID","EduTotal","TermID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LLJX = new Field("LLJX","EduTotal","LLJX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PJXS = new Field("PJXS","EduTotal","PJXS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field KS = new Field("KS","EduTotal","KS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JXSX = new Field("JXSX","EduTotal","JXSX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JXSXKW = new Field("JXSXKW","EduTotal","JXSXKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field KCSJ = new Field("KCSJ","EduTotal","KCSJ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field KCSJKW = new Field("KCSJKW","EduTotal","KCSJKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCSX = new Field("SCSX","EduTotal","SCSX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCSXKW = new Field("SCSXKW","EduTotal","SCSXKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BYSJ = new Field("BYSJ","EduTotal","BYSJ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BYSJKW = new Field("BYSJKW","EduTotal","BYSJKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JX = new Field("JX","EduTotal","JX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GYLD = new Field("GYLD","EduTotal","GYLD");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GYLDKW = new Field("GYLDKW","EduTotal","GYLDKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JD = new Field("JD","EduTotal","JD");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RXJY = new Field("RXJY","EduTotal","RXJY");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BYJY = new Field("BYJY","EduTotal","BYJY");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BYJYKW = new Field("BYJYKW","EduTotal","BYJYKW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JQ = new Field("JQ","EduTotal","JQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HJ = new Field("HJ","EduTotal","HJ");
		}
		#endregion


	}
}

