//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Excellent 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Excellent")]
	[Serializable]
	public partial class Excellent : Entity 
	{
		#region Model
		private int _EXID;
		private int? _Atyid;
		private int? _Stdid;
		private int? _ANums;
		private int? _BNums;
		/// <summary>
		/// 
		/// </summary>
		public int EXID
		{
			get{ return _EXID; }
			set
			{
				this.OnPropertyValueChange(_.EXID,_EXID,value);
				this._EXID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Atyid
		{
			get{ return _Atyid; }
			set
			{
				this.OnPropertyValueChange(_.Atyid,_Atyid,value);
				this._Atyid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ANums
		{
			get{ return _ANums; }
			set
			{
				this.OnPropertyValueChange(_.ANums,_ANums,value);
				this._ANums=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? BNums
		{
			get{ return _BNums; }
			set
			{
				this.OnPropertyValueChange(_.BNums,_BNums,value);
				this._BNums=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.EXID;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.EXID,
				_.Atyid,
				_.Stdid,
				_.ANums,
				_.BNums};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._EXID,
				this._Atyid,
				this._Stdid,
				this._ANums,
				this._BNums};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Excellent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EXID = new Field("EXID","Excellent","EXID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atyid = new Field("atyid","Excellent","atyid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("stdid","Excellent","stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ANums = new Field("ANums","Excellent","ANums");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BNums = new Field("BNums","Excellent","BNums");
		}
		#endregion


	}
}

