//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ExpRoom 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ExpRoom")]
	[Serializable]
	public partial class ExpRoom : Entity 
	{
		#region Model
		private int _ERID;
		private int? _DeptID;
		private string _ERoomName;
		private string _Address;
		private int? _PSIDA;
		private int? _PSIDB;
		private int? _GroupNum;
		/// <summary>
		/// 
		/// </summary>
		public int ERID
		{
			get{ return _ERID; }
			set
			{
				this.OnPropertyValueChange(_.ERID,_ERID,value);
				this._ERID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DeptID
		{
			get{ return _DeptID; }
			set
			{
				this.OnPropertyValueChange(_.DeptID,_DeptID,value);
				this._DeptID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ERoomName
		{
			get{ return _ERoomName; }
			set
			{
				this.OnPropertyValueChange(_.ERoomName,_ERoomName,value);
				this._ERoomName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSIDA
		{
			get{ return _PSIDA; }
			set
			{
				this.OnPropertyValueChange(_.PSIDA,_PSIDA,value);
				this._PSIDA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSIDB
		{
			get{ return _PSIDB; }
			set
			{
				this.OnPropertyValueChange(_.PSIDB,_PSIDB,value);
				this._PSIDB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GroupNum
		{
			get{ return _GroupNum; }
			set
			{
				this.OnPropertyValueChange(_.GroupNum,_GroupNum,value);
				this._GroupNum=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ERID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ERID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ERID,
				_.DeptID,
				_.ERoomName,
				_.Address,
				_.PSIDA,
				_.PSIDB,
				_.GroupNum};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ERID,
				this._DeptID,
				this._ERoomName,
				this._Address,
				this._PSIDA,
				this._PSIDB,
				this._GroupNum};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ExpRoom");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ERID = new Field("ERID","ExpRoom","ERID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptID = new Field("DeptID","ExpRoom","DeptID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ERoomName = new Field("ERoomName","ExpRoom","ERoomName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address","ExpRoom","Address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSIDA = new Field("PSIDA","ExpRoom","PSIDA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSIDB = new Field("PSIDB","ExpRoom","PSIDB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GroupNum = new Field("GroupNum","ExpRoom","GroupNum");
		}
		#endregion


	}
}

