//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ExpUser 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ExpUser")]
	[Serializable]
	public partial class ExpUser : Entity 
	{
		#region Model
		private int _ExpUID;
		private int? _DeptID;
		private string _UserName;
		private string _Account;
		private string _Psw;
		private int? _RoleID;
		private DateTime? _BuildDate;
		private string _Oper;
		private DateTime? _LastDate;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int ExpUID
		{
			get{ return _ExpUID; }
			set
			{
				this.OnPropertyValueChange(_.ExpUID,_ExpUID,value);
				this._ExpUID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DeptID
		{
			get{ return _DeptID; }
			set
			{
				this.OnPropertyValueChange(_.DeptID,_DeptID,value);
				this._DeptID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange(_.UserName,_UserName,value);
				this._UserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Account
		{
			get{ return _Account; }
			set
			{
				this.OnPropertyValueChange(_.Account,_Account,value);
				this._Account=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Psw
		{
			get{ return _Psw; }
			set
			{
				this.OnPropertyValueChange(_.Psw,_Psw,value);
				this._Psw=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? RoleID
		{
			get{ return _RoleID; }
			set
			{
				this.OnPropertyValueChange(_.RoleID,_RoleID,value);
				this._RoleID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? BuildDate
		{
			get{ return _BuildDate; }
			set
			{
				this.OnPropertyValueChange(_.BuildDate,_BuildDate,value);
				this._BuildDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Oper
		{
			get{ return _Oper; }
			set
			{
				this.OnPropertyValueChange(_.Oper,_Oper,value);
				this._Oper=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ExpUID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ExpUID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ExpUID,
				_.DeptID,
				_.UserName,
				_.Account,
				_.Psw,
				_.RoleID,
				_.BuildDate,
				_.Oper,
				_.LastDate,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ExpUID,
				this._DeptID,
				this._UserName,
				this._Account,
				this._Psw,
				this._RoleID,
				this._BuildDate,
				this._Oper,
				this._LastDate,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ExpUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExpUID = new Field("ExpUID","ExpUser","ExpUID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptID = new Field("DeptID","ExpUser","DeptID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName","ExpUser","UserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Account = new Field("Account","ExpUser","Account");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Psw = new Field("Psw","ExpUser","Psw");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleID = new Field("RoleID","ExpUser","RoleID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BuildDate = new Field("BuildDate","ExpUser","BuildDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Oper = new Field("Oper","ExpUser","Oper");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","ExpUser","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","ExpUser","state");
		}
		#endregion


	}
}

