//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Graduate 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Graduate")]
	[Serializable]
	public partial class Graduate : Entity 
	{
		#region Model
		private int _STGID;
		private int? _AtyID;
		private int? _Stdid;
		private int? _CLID;
		private int? _GRID;
		private int? _DeptID;
		private int? _SPID;
		private string _Xuewei;
		private string _BiYe;
		private int? _MainBJGNum;
		private decimal? _MBJGSource;
		private int? _BJGNum;
		private decimal? _BJGSource;
		private int? _MainLostNum;
		private decimal? _MLSource;
		private int? _LostNum;
		private decimal? _LostSource;
		private decimal? _GetSource;
		private decimal? _LLSource;
		private decimal? _SJSource;
		private decimal? _PubSource;
		private decimal? _MainAvgSource;
		private string _KSH;
		private string _BYZID;
		private string _XWZID;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int STGID
		{
			get{ return _STGID; }
			set
			{
				this.OnPropertyValueChange(_.STGID,_STGID,value);
				this._STGID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AtyID
		{
			get{ return _AtyID; }
			set
			{
				this.OnPropertyValueChange(_.AtyID,_AtyID,value);
				this._AtyID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CLID
		{
			get{ return _CLID; }
			set
			{
				this.OnPropertyValueChange(_.CLID,_CLID,value);
				this._CLID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GRID
		{
			get{ return _GRID; }
			set
			{
				this.OnPropertyValueChange(_.GRID,_GRID,value);
				this._GRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DeptID
		{
			get{ return _DeptID; }
			set
			{
				this.OnPropertyValueChange(_.DeptID,_DeptID,value);
				this._DeptID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SPID
		{
			get{ return _SPID; }
			set
			{
				this.OnPropertyValueChange(_.SPID,_SPID,value);
				this._SPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Xuewei
		{
			get{ return _Xuewei; }
			set
			{
				this.OnPropertyValueChange(_.Xuewei,_Xuewei,value);
				this._Xuewei=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string BiYe
		{
			get{ return _BiYe; }
			set
			{
				this.OnPropertyValueChange(_.BiYe,_BiYe,value);
				this._BiYe=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MainBJGNum
		{
			get{ return _MainBJGNum; }
			set
			{
				this.OnPropertyValueChange(_.MainBJGNum,_MainBJGNum,value);
				this._MainBJGNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? MBJGSource
		{
			get{ return _MBJGSource; }
			set
			{
				this.OnPropertyValueChange(_.MBJGSource,_MBJGSource,value);
				this._MBJGSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? BJGNum
		{
			get{ return _BJGNum; }
			set
			{
				this.OnPropertyValueChange(_.BJGNum,_BJGNum,value);
				this._BJGNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BJGSource
		{
			get{ return _BJGSource; }
			set
			{
				this.OnPropertyValueChange(_.BJGSource,_BJGSource,value);
				this._BJGSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MainLostNum
		{
			get{ return _MainLostNum; }
			set
			{
				this.OnPropertyValueChange(_.MainLostNum,_MainLostNum,value);
				this._MainLostNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? MLSource
		{
			get{ return _MLSource; }
			set
			{
				this.OnPropertyValueChange(_.MLSource,_MLSource,value);
				this._MLSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LostNum
		{
			get{ return _LostNum; }
			set
			{
				this.OnPropertyValueChange(_.LostNum,_LostNum,value);
				this._LostNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? LostSource
		{
			get{ return _LostSource; }
			set
			{
				this.OnPropertyValueChange(_.LostSource,_LostSource,value);
				this._LostSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? GetSource
		{
			get{ return _GetSource; }
			set
			{
				this.OnPropertyValueChange(_.GetSource,_GetSource,value);
				this._GetSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? LLSource
		{
			get{ return _LLSource; }
			set
			{
				this.OnPropertyValueChange(_.LLSource,_LLSource,value);
				this._LLSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SJSource
		{
			get{ return _SJSource; }
			set
			{
				this.OnPropertyValueChange(_.SJSource,_SJSource,value);
				this._SJSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PubSource
		{
			get{ return _PubSource; }
			set
			{
				this.OnPropertyValueChange(_.PubSource,_PubSource,value);
				this._PubSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? MainAvgSource
		{
			get{ return _MainAvgSource; }
			set
			{
				this.OnPropertyValueChange(_.MainAvgSource,_MainAvgSource,value);
				this._MainAvgSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string KSH
		{
			get{ return _KSH; }
			set
			{
				this.OnPropertyValueChange(_.KSH,_KSH,value);
				this._KSH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string BYZID
		{
			get{ return _BYZID; }
			set
			{
				this.OnPropertyValueChange(_.BYZID,_BYZID,value);
				this._BYZID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string XWZID
		{
			get{ return _XWZID; }
			set
			{
				this.OnPropertyValueChange(_.XWZID,_XWZID,value);
				this._XWZID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.STGID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.STGID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.STGID,
				_.AtyID,
				_.Stdid,
				_.CLID,
				_.GRID,
				_.DeptID,
				_.SPID,
				_.Xuewei,
				_.BiYe,
				_.MainBJGNum,
				_.MBJGSource,
				_.BJGNum,
				_.BJGSource,
				_.MainLostNum,
				_.MLSource,
				_.LostNum,
				_.LostSource,
				_.GetSource,
				_.LLSource,
				_.SJSource,
				_.PubSource,
				_.MainAvgSource,
				_.KSH,
				_.BYZID,
				_.XWZID,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._STGID,
				this._AtyID,
				this._Stdid,
				this._CLID,
				this._GRID,
				this._DeptID,
				this._SPID,
				this._Xuewei,
				this._BiYe,
				this._MainBJGNum,
				this._MBJGSource,
				this._BJGNum,
				this._BJGSource,
				this._MainLostNum,
				this._MLSource,
				this._LostNum,
				this._LostSource,
				this._GetSource,
				this._LLSource,
				this._SJSource,
				this._PubSource,
				this._MainAvgSource,
				this._KSH,
				this._BYZID,
				this._XWZID,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Graduate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STGID = new Field("STGID","Graduate","STGID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AtyID = new Field("AtyID","Graduate","AtyID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("Stdid","Graduate","Stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLID = new Field("CLID","Graduate","CLID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GRID = new Field("GRID","Graduate","GRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptID = new Field("DeptID","Graduate","DeptID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPID = new Field("SPID","Graduate","SPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Xuewei = new Field("Xuewei","Graduate","Xuewei");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BiYe = new Field("BiYe","Graduate","BiYe");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MainBJGNum = new Field("MainBJGNum","Graduate","MainBJGNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MBJGSource = new Field("MBJGSource","Graduate","MBJGSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BJGNum = new Field("BJGNum","Graduate","BJGNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BJGSource = new Field("BJGSource","Graduate","BJGSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MainLostNum = new Field("MainLostNum","Graduate","MainLostNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MLSource = new Field("MLSource","Graduate","MLSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LostNum = new Field("LostNum","Graduate","LostNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LostSource = new Field("LostSource","Graduate","LostSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GetSource = new Field("GetSource","Graduate","GetSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LLSource = new Field("LLSource","Graduate","LLSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SJSource = new Field("SJSource","Graduate","SJSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PubSource = new Field("PubSource","Graduate","PubSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MainAvgSource = new Field("MainAvgSource","Graduate","MainAvgSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field KSH = new Field("KSH","Graduate","KSH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BYZID = new Field("BYZID","Graduate","BYZID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XWZID = new Field("XWZID","Graduate","XWZID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","Graduate","State");
		}
		#endregion


	}
}

