//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Graph 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Graph")]
	[Serializable]
	public partial class Graph : Entity 
	{
		#region Model
		private int _GraphID;
		private int? _CCID;
		private string _ChpNo;
		private string _ChpName;
		private string _GraphNo;
		private string _GraphName;
		private string _Graphcont;
		private int? _Graphtotal;
		private string _Grapost;
		/// <summary>
		/// 
		/// </summary>
		public int GraphID
		{
			get{ return _GraphID; }
			set
			{
				this.OnPropertyValueChange(_.GraphID,_GraphID,value);
				this._GraphID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpNo
		{
			get{ return _ChpNo; }
			set
			{
				this.OnPropertyValueChange(_.ChpNo,_ChpNo,value);
				this._ChpNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpName
		{
			get{ return _ChpName; }
			set
			{
				this.OnPropertyValueChange(_.ChpName,_ChpName,value);
				this._ChpName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GraphNo
		{
			get{ return _GraphNo; }
			set
			{
				this.OnPropertyValueChange(_.GraphNo,_GraphNo,value);
				this._GraphNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GraphName
		{
			get{ return _GraphName; }
			set
			{
				this.OnPropertyValueChange(_.GraphName,_GraphName,value);
				this._GraphName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Graphcont
		{
			get{ return _Graphcont; }
			set
			{
				this.OnPropertyValueChange(_.Graphcont,_Graphcont,value);
				this._Graphcont=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Graphtotal
		{
			get{ return _Graphtotal; }
			set
			{
				this.OnPropertyValueChange(_.Graphtotal,_Graphtotal,value);
				this._Graphtotal=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Grapost
		{
			get{ return _Grapost; }
			set
			{
				this.OnPropertyValueChange(_.Grapost,_Grapost,value);
				this._Grapost=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.GraphID,
				_.CCID,
				_.ChpNo,
				_.ChpName,
				_.GraphNo,
				_.GraphName,
				_.Graphcont,
				_.Graphtotal,
				_.Grapost};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._GraphID,
				this._CCID,
				this._ChpNo,
				this._ChpName,
				this._GraphNo,
				this._GraphName,
				this._Graphcont,
				this._Graphtotal,
				this._Grapost};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Graph");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GraphID = new Field("GraphID","Graph","GraphID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","Graph","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpNo = new Field("ChpNo","Graph","ChpNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpName = new Field("ChpName","Graph","ChpName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GraphNo = new Field("GraphNo","Graph","GraphNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GraphName = new Field("GraphName","Graph","GraphName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Graphcont = new Field("Graphcont","Graph","Graphcont");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Graphtotal = new Field("Graphtotal","Graph","Graphtotal");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Grapost = new Field("Grapost","Graph","Grapost");
		}
		#endregion


	}
}

