//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ImportantDiff 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ImportantDiff")]
	[Serializable]
	public partial class ImportantDiff : Entity 
	{
		#region Model
		private int _ImDiID;
		private int? _CCID;
		private string _ChNo;
		private string _Content;
		private string _Type;
		private string _AN;
		private int? _CHPID;
		private string _IMDINO;
		/// <summary>
		/// 
		/// </summary>
		public int ImDiID
		{
			get{ return _ImDiID; }
			set
			{
				this.OnPropertyValueChange(_.ImDiID,_ImDiID,value);
				this._ImDiID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChNo
		{
			get{ return _ChNo; }
			set
			{
				this.OnPropertyValueChange(_.ChNo,_ChNo,value);
				this._ChNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AN
		{
			get{ return _AN; }
			set
			{
				this.OnPropertyValueChange(_.AN,_AN,value);
				this._AN=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CHPID
		{
			get{ return _CHPID; }
			set
			{
				this.OnPropertyValueChange(_.CHPID,_CHPID,value);
				this._CHPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IMDINO
		{
			get{ return _IMDINO; }
			set
			{
				this.OnPropertyValueChange(_.IMDINO,_IMDINO,value);
				this._IMDINO=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ImDiID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ImDiID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ImDiID,
				_.CCID,
				_.ChNo,
				_.Content,
				_.Type,
				_.AN,
				_.CHPID,
				_.IMDINO};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ImDiID,
				this._CCID,
				this._ChNo,
				this._Content,
				this._Type,
				this._AN,
				this._CHPID,
				this._IMDINO};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ImportantDiff");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ImDiID = new Field("ImDiID","ImportantDiff","ImDiID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","ImportantDiff","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChNo = new Field("ChNo","ImportantDiff","ChNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","ImportantDiff","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","ImportantDiff","Type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AN = new Field("AN","ImportantDiff","AN");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CHPID = new Field("CHPID","ImportantDiff","CHPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IMDINO = new Field("IMDINO","ImportantDiff","IMDINO");
		}
		#endregion


	}
}

