//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Paper 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("paper")]
	[Serializable]
	public partial class Paper : Entity 
	{
		#region Model
		private int _PID;
		private string _Papersort;
		private int? _Source;
		/// <summary>
		/// 
		/// </summary>
		public int PID
		{
			get{ return _PID; }
			set
			{
				this.OnPropertyValueChange(_.PID,_PID,value);
				this._PID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Papersort
		{
			get{ return _Papersort; }
			set
			{
				this.OnPropertyValueChange(_.Papersort,_Papersort,value);
				this._Papersort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.PID;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PID,
				_.Papersort,
				_.Source};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PID,
				this._Papersort,
				this._Source};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","paper");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PID = new Field("PID","paper","PID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Papersort = new Field("papersort","paper","papersort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("source","paper","source");
		}
		#endregion


	}
}

