//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类PJ_Account 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PJ_Account")]
	[Serializable]
	public partial class PJ_Account : Entity 
	{
		#region Model
		private int _PAID;
		private int? _SubJID;
		private int? _APDID;
		private decimal? _AvgSource;
		private string _AvgLev;
		private decimal? _Source;
		private decimal? _Standard;
		private int? _SANum;
		private int? _SBNum;
		private int? _SCNum;
		private int? _SDNum;
		private int? _SENum;
		/// <summary>
		/// 
		/// </summary>
		public int PAID
		{
			get{ return _PAID; }
			set
			{
				this.OnPropertyValueChange(_.PAID,_PAID,value);
				this._PAID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SubJID
		{
			get{ return _SubJID; }
			set
			{
				this.OnPropertyValueChange(_.SubJID,_SubJID,value);
				this._SubJID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? APDID
		{
			get{ return _APDID; }
			set
			{
				this.OnPropertyValueChange(_.APDID,_APDID,value);
				this._APDID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? AvgSource
		{
			get{ return _AvgSource; }
			set
			{
				this.OnPropertyValueChange(_.AvgSource,_AvgSource,value);
				this._AvgSource=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AvgLev
		{
			get{ return _AvgLev; }
			set
			{
				this.OnPropertyValueChange(_.AvgLev,_AvgLev,value);
				this._AvgLev=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Standard
		{
			get{ return _Standard; }
			set
			{
				this.OnPropertyValueChange(_.Standard,_Standard,value);
				this._Standard=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SANum
		{
			get{ return _SANum; }
			set
			{
				this.OnPropertyValueChange(_.SANum,_SANum,value);
				this._SANum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SBNum
		{
			get{ return _SBNum; }
			set
			{
				this.OnPropertyValueChange(_.SBNum,_SBNum,value);
				this._SBNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SCNum
		{
			get{ return _SCNum; }
			set
			{
				this.OnPropertyValueChange(_.SCNum,_SCNum,value);
				this._SCNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SDNum
		{
			get{ return _SDNum; }
			set
			{
				this.OnPropertyValueChange(_.SDNum,_SDNum,value);
				this._SDNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SENum
		{
			get{ return _SENum; }
			set
			{
				this.OnPropertyValueChange(_.SENum,_SENum,value);
				this._SENum=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.PAID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.PAID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PAID,
				_.SubJID,
				_.APDID,
				_.AvgSource,
				_.AvgLev,
				_.Source,
				_.Standard,
				_.SANum,
				_.SBNum,
				_.SCNum,
				_.SDNum,
				_.SENum};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PAID,
				this._SubJID,
				this._APDID,
				this._AvgSource,
				this._AvgLev,
				this._Source,
				this._Standard,
				this._SANum,
				this._SBNum,
				this._SCNum,
				this._SDNum,
				this._SENum};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","PJ_Account");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PAID = new Field("PAID","PJ_Account","PAID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubJID = new Field("SubJID","PJ_Account","SubJID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APDID = new Field("APDID","PJ_Account","APDID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AvgSource = new Field("AvgSource","PJ_Account","AvgSource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AvgLev = new Field("AvgLev","PJ_Account","AvgLev");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","PJ_Account","Source");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Standard = new Field("Standard","PJ_Account","Standard");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SANum = new Field("SANum","PJ_Account","SANum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SBNum = new Field("SBNum","PJ_Account","SBNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCNum = new Field("SCNum","PJ_Account","SCNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SDNum = new Field("SDNum","PJ_Account","SDNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SENum = new Field("SENum","PJ_Account","SENum");
		}
		#endregion


	}
}

