//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类PKCondition 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PKCondition")]
	[Serializable]
	public partial class PKCondition : Entity 
	{
		#region Model
		private int _PKEID;
		private int? _Atyid;
		private string _Sort;
		private string _Content;
		private int? _PSID;
		private int? _CCID;
		private int? _TCID;
		private int? _CRID;
		private int? _DayOFWeek;
		private string _SectionTH;
		private int? _StartWeek;
		private int? _EndWeek;
		private string _DSZ;
		private string _Memo;
		private string _Limit;
		/// <summary>
		/// 
		/// </summary>
		public int PKEID
		{
			get{ return _PKEID; }
			set
			{
				this.OnPropertyValueChange(_.PKEID,_PKEID,value);
				this._PKEID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Atyid
		{
			get{ return _Atyid; }
			set
			{
				this.OnPropertyValueChange(_.Atyid,_Atyid,value);
				this._Atyid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TCID
		{
			get{ return _TCID; }
			set
			{
				this.OnPropertyValueChange(_.TCID,_TCID,value);
				this._TCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CRID
		{
			get{ return _CRID; }
			set
			{
				this.OnPropertyValueChange(_.CRID,_CRID,value);
				this._CRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DayOFWeek
		{
			get{ return _DayOFWeek; }
			set
			{
				this.OnPropertyValueChange(_.DayOFWeek,_DayOFWeek,value);
				this._DayOFWeek=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SectionTH
		{
			get{ return _SectionTH; }
			set
			{
				this.OnPropertyValueChange(_.SectionTH,_SectionTH,value);
				this._SectionTH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? StartWeek
		{
			get{ return _StartWeek; }
			set
			{
				this.OnPropertyValueChange(_.StartWeek,_StartWeek,value);
				this._StartWeek=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? EndWeek
		{
			get{ return _EndWeek; }
			set
			{
				this.OnPropertyValueChange(_.EndWeek,_EndWeek,value);
				this._EndWeek=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DSZ
		{
			get{ return _DSZ; }
			set
			{
				this.OnPropertyValueChange(_.DSZ,_DSZ,value);
				this._DSZ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange(_.Memo,_Memo,value);
				this._Memo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Limit
		{
			get{ return _Limit; }
			set
			{
				this.OnPropertyValueChange(_.Limit,_Limit,value);
				this._Limit=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.PKEID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.PKEID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PKEID,
				_.Atyid,
				_.Sort,
				_.Content,
				_.PSID,
				_.CCID,
				_.TCID,
				_.CRID,
				_.DayOFWeek,
				_.SectionTH,
				_.StartWeek,
				_.EndWeek,
				_.DSZ,
				_.Memo,
				_.Limit};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PKEID,
				this._Atyid,
				this._Sort,
				this._Content,
				this._PSID,
				this._CCID,
				this._TCID,
				this._CRID,
				this._DayOFWeek,
				this._SectionTH,
				this._StartWeek,
				this._EndWeek,
				this._DSZ,
				this._Memo,
				this._Limit};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","PKCondition");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PKEID = new Field("PKEID","PKCondition","PKEID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atyid = new Field("atyid","PKCondition","atyid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sort = new Field("Sort","PKCondition","Sort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","PKCondition","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","PKCondition","PSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","PKCondition","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TCID = new Field("TCID","PKCondition","TCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRID = new Field("CRID","PKCondition","CRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DayOFWeek = new Field("DayOFWeek","PKCondition","DayOFWeek");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SectionTH = new Field("SectionTH","PKCondition","SectionTH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartWeek = new Field("StartWeek","PKCondition","StartWeek");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndWeek = new Field("EndWeek","PKCondition","EndWeek");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DSZ = new Field("DSZ","PKCondition","DSZ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Memo = new Field("Memo","PKCondition","Memo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Limit = new Field("Limit","PKCondition","Limit");
		}
		#endregion


	}
}

