//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类SchoolNo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("SchoolNo")]
	[Serializable]
	public partial class SchoolNo : Entity 
	{
		#region Model
		private int _SCID;
		private int? _XH;
		private string _Schoolname;
		private string _SCNName;
		private int? _MaxNum;
		private string _ShengShi;
		private string _Daxing;
		private string _DaBH;
		private string _PsNum;
		private string _Maker;
		private string _TelA;
		private string _Manager;
		private string _TelB;
		private string _Looker;
		private string _TelC;
		/// <summary>
		/// 
		/// </summary>
		public int SCID
		{
			get{ return _SCID; }
			set
			{
				this.OnPropertyValueChange(_.SCID,_SCID,value);
				this._SCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? XH
		{
			get{ return _XH; }
			set
			{
				this.OnPropertyValueChange(_.XH,_XH,value);
				this._XH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Schoolname
		{
			get{ return _Schoolname; }
			set
			{
				this.OnPropertyValueChange(_.Schoolname,_Schoolname,value);
				this._Schoolname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SCNName
		{
			get{ return _SCNName; }
			set
			{
				this.OnPropertyValueChange(_.SCNName,_SCNName,value);
				this._SCNName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MaxNum
		{
			get{ return _MaxNum; }
			set
			{
				this.OnPropertyValueChange(_.MaxNum,_MaxNum,value);
				this._MaxNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ShengShi
		{
			get{ return _ShengShi; }
			set
			{
				this.OnPropertyValueChange(_.ShengShi,_ShengShi,value);
				this._ShengShi=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Daxing
		{
			get{ return _Daxing; }
			set
			{
				this.OnPropertyValueChange(_.Daxing,_Daxing,value);
				this._Daxing=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DaBH
		{
			get{ return _DaBH; }
			set
			{
				this.OnPropertyValueChange(_.DaBH,_DaBH,value);
				this._DaBH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PsNum
		{
			get{ return _PsNum; }
			set
			{
				this.OnPropertyValueChange(_.PsNum,_PsNum,value);
				this._PsNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Maker
		{
			get{ return _Maker; }
			set
			{
				this.OnPropertyValueChange(_.Maker,_Maker,value);
				this._Maker=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TelA
		{
			get{ return _TelA; }
			set
			{
				this.OnPropertyValueChange(_.TelA,_TelA,value);
				this._TelA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Manager
		{
			get{ return _Manager; }
			set
			{
				this.OnPropertyValueChange(_.Manager,_Manager,value);
				this._Manager=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TelB
		{
			get{ return _TelB; }
			set
			{
				this.OnPropertyValueChange(_.TelB,_TelB,value);
				this._TelB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Looker
		{
			get{ return _Looker; }
			set
			{
				this.OnPropertyValueChange(_.Looker,_Looker,value);
				this._Looker=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TelC
		{
			get{ return _TelC; }
			set
			{
				this.OnPropertyValueChange(_.TelC,_TelC,value);
				this._TelC=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.SCID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.SCID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SCID,
				_.XH,
				_.Schoolname,
				_.SCNName,
				_.MaxNum,
				_.ShengShi,
				_.Daxing,
				_.DaBH,
				_.PsNum,
				_.Maker,
				_.TelA,
				_.Manager,
				_.TelB,
				_.Looker,
				_.TelC};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SCID,
				this._XH,
				this._Schoolname,
				this._SCNName,
				this._MaxNum,
				this._ShengShi,
				this._Daxing,
				this._DaBH,
				this._PsNum,
				this._Maker,
				this._TelA,
				this._Manager,
				this._TelB,
				this._Looker,
				this._TelC};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","SchoolNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCID = new Field("SCID","SchoolNo","SCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XH = new Field("XH","SchoolNo","XH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Schoolname = new Field("Schoolname","SchoolNo","Schoolname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SCNName = new Field("SCNName","SchoolNo","SCNName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MaxNum = new Field("MaxNum","SchoolNo","MaxNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ShengShi = new Field("ShengShi","SchoolNo","ShengShi");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Daxing = new Field("Daxing","SchoolNo","Daxing");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DaBH = new Field("DaBH","SchoolNo","DaBH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PsNum = new Field("PsNum","SchoolNo","PsNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Maker = new Field("Maker","SchoolNo","Maker");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TelA = new Field("TelA","SchoolNo","TelA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Manager = new Field("Manager","SchoolNo","Manager");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TelB = new Field("TelB","SchoolNo","TelB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Looker = new Field("Looker","SchoolNo","Looker");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TelC = new Field("TelC","SchoolNo","TelC");
		}
		#endregion


	}
}

