//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类SQuestion 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("SQuestion")]
	[Serializable]
	public partial class SQuestion : Entity 
	{
		#region Model
		private int _SQID;
		private string _Title;
		private string _Content;
		private DateTime _STQDate;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int SQID
		{
			get{ return _SQID; }
			set
			{
				this.OnPropertyValueChange(_.SQID,_SQID,value);
				this._SQID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime STQDate
		{
			get{ return _STQDate; }
			set
			{
				this.OnPropertyValueChange(_.STQDate,_STQDate,value);
				this._STQDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.SQID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.SQID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SQID,
				_.Title,
				_.Content,
				_.STQDate,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SQID,
				this._Title,
				this._Content,
				this._STQDate,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","SQuestion");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SQID = new Field("SQID","SQuestion","SQID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","SQuestion","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","SQuestion","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STQDate = new Field("STQDate","SQuestion","STQDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","SQuestion","state");
		}
		#endregion


	}
}

