//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类StatByAll 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("StatByAll")]
	[Serializable]
	public partial class StatByAll : Entity 
	{
		#region Model
		private int _STAID;
		private int? _AtyID;
		private int? _CCID;
		private int? _LevID;
		private string _LevContent;
		private int? _PSNum;
		private int? _AllNum;
		private string _AB;
		/// <summary>
		/// 
		/// </summary>
		public int STAID
		{
			get{ return _STAID; }
			set
			{
				this.OnPropertyValueChange(_.STAID,_STAID,value);
				this._STAID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AtyID
		{
			get{ return _AtyID; }
			set
			{
				this.OnPropertyValueChange(_.AtyID,_AtyID,value);
				this._AtyID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LevID
		{
			get{ return _LevID; }
			set
			{
				this.OnPropertyValueChange(_.LevID,_LevID,value);
				this._LevID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LevContent
		{
			get{ return _LevContent; }
			set
			{
				this.OnPropertyValueChange(_.LevContent,_LevContent,value);
				this._LevContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSNum
		{
			get{ return _PSNum; }
			set
			{
				this.OnPropertyValueChange(_.PSNum,_PSNum,value);
				this._PSNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AllNum
		{
			get{ return _AllNum; }
			set
			{
				this.OnPropertyValueChange(_.AllNum,_AllNum,value);
				this._AllNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AB
		{
			get{ return _AB; }
			set
			{
				this.OnPropertyValueChange(_.AB,_AB,value);
				this._AB=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.STAID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.STAID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.STAID,
				_.AtyID,
				_.CCID,
				_.LevID,
				_.LevContent,
				_.PSNum,
				_.AllNum,
				_.AB};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._STAID,
				this._AtyID,
				this._CCID,
				this._LevID,
				this._LevContent,
				this._PSNum,
				this._AllNum,
				this._AB};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","StatByAll");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STAID = new Field("STAID","StatByAll","STAID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AtyID = new Field("AtyID","StatByAll","AtyID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","StatByAll","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LevID = new Field("LevID","StatByAll","LevID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LevContent = new Field("LevContent","StatByAll","LevContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSNum = new Field("PSNum","StatByAll","PSNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllNum = new Field("AllNum","StatByAll","AllNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AB = new Field("AB","StatByAll","AB");
		}
		#endregion


	}
}

