//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类StuDangLiang 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("StuDangLiang")]
	[Serializable]
	public partial class StuDangLiang : Entity 
	{
		#region Model
		private int _DLID;
		private string _StuSort;
		private decimal? _DLNum;
		/// <summary>
		/// 
		/// </summary>
		public int DLID
		{
			get{ return _DLID; }
			set
			{
				this.OnPropertyValueChange(_.DLID,_DLID,value);
				this._DLID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StuSort
		{
			get{ return _StuSort; }
			set
			{
				this.OnPropertyValueChange(_.StuSort,_StuSort,value);
				this._StuSort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DLNum
		{
			get{ return _DLNum; }
			set
			{
				this.OnPropertyValueChange(_.DLNum,_DLNum,value);
				this._DLNum=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.DLID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.DLID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.DLID,
				_.StuSort,
				_.DLNum};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._DLID,
				this._StuSort,
				this._DLNum};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","StuDangLiang");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DLID = new Field("DLID","StuDangLiang","DLID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuSort = new Field("StuSort","StuDangLiang","StuSort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DLNum = new Field("DLNum","StuDangLiang","DLNum");
		}
		#endregion


	}
}

