//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Studyhall 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Studyhall")]
	[Serializable]
	public partial class Studyhall : Entity 
	{
		#region Model
		private int _ZXID;
		private int? _CCID;
		private int? _ATYID;
		private string _IMG;
		private int? _OperID;
		private string _ImgSort;
		private string _Introduction;
		private string _MannerNO;
		/// <summary>
		/// 
		/// </summary>
		public int ZXID
		{
			get{ return _ZXID; }
			set
			{
				this.OnPropertyValueChange(_.ZXID,_ZXID,value);
				this._ZXID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATYID
		{
			get{ return _ATYID; }
			set
			{
				this.OnPropertyValueChange(_.ATYID,_ATYID,value);
				this._ATYID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IMG
		{
			get{ return _IMG; }
			set
			{
				this.OnPropertyValueChange(_.IMG,_IMG,value);
				this._IMG=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? OperID
		{
			get{ return _OperID; }
			set
			{
				this.OnPropertyValueChange(_.OperID,_OperID,value);
				this._OperID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ImgSort
		{
			get{ return _ImgSort; }
			set
			{
				this.OnPropertyValueChange(_.ImgSort,_ImgSort,value);
				this._ImgSort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Introduction
		{
			get{ return _Introduction; }
			set
			{
				this.OnPropertyValueChange(_.Introduction,_Introduction,value);
				this._Introduction=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MannerNO
		{
			get{ return _MannerNO; }
			set
			{
				this.OnPropertyValueChange(_.MannerNO,_MannerNO,value);
				this._MannerNO=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ZXID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ZXID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ZXID,
				_.CCID,
				_.ATYID,
				_.IMG,
				_.OperID,
				_.ImgSort,
				_.Introduction,
				_.MannerNO};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ZXID,
				this._CCID,
				this._ATYID,
				this._IMG,
				this._OperID,
				this._ImgSort,
				this._Introduction,
				this._MannerNO};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Studyhall");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZXID = new Field("ZXID","Studyhall","ZXID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","Studyhall","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATYID = new Field("ATYID","Studyhall","ATYID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IMG = new Field("IMG","Studyhall","IMG");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OperID = new Field("operID","Studyhall","operID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ImgSort = new Field("ImgSort","Studyhall","ImgSort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Introduction = new Field("Introduction","Studyhall","Introduction");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MannerNO = new Field("MannerNO","Studyhall","MannerNO");
		}
		#endregion


	}
}

