//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Stumark 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Stumark")]
	[Serializable]
	public partial class Stumark : Entity 
	{
		#region Model
		private int _STMID;
		private string _Mark;
		private string _Markname;
		/// <summary>
		/// 
		/// </summary>
		public int STMID
		{
			get{ return _STMID; }
			set
			{
				this.OnPropertyValueChange(_.STMID,_STMID,value);
				this._STMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Mark
		{
			get{ return _Mark; }
			set
			{
				this.OnPropertyValueChange(_.Mark,_Mark,value);
				this._Mark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Markname
		{
			get{ return _Markname; }
			set
			{
				this.OnPropertyValueChange(_.Markname,_Markname,value);
				this._Markname=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.STMID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.STMID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.STMID,
				_.Mark,
				_.Markname};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._STMID,
				this._Mark,
				this._Markname};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Stumark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STMID = new Field("STMID","Stumark","STMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Mark = new Field("Mark","Stumark","Mark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Markname = new Field("Markname","Stumark","Markname");
		}
		#endregion


	}
}

