//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类StuPlanTerm 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("StuPlanTerm")]
	[Serializable]
	public partial class StuPlanTerm : Entity 
	{
		#region Model
		private int _SPTID;
		private int? _Stdid;
		private int? _TMID;
		private decimal? _Source;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int SPTID
		{
			get{ return _SPTID; }
			set
			{
				this.OnPropertyValueChange(_.SPTID,_SPTID,value);
				this._SPTID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TMID
		{
			get{ return _TMID; }
			set
			{
				this.OnPropertyValueChange(_.TMID,_TMID,value);
				this._TMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.SPTID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.SPTID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SPTID,
				_.Stdid,
				_.TMID,
				_.Source,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SPTID,
				this._Stdid,
				this._TMID,
				this._Source,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","StuPlanTerm");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPTID = new Field("SPTID","StuPlanTerm","SPTID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("Stdid","StuPlanTerm","Stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TMID = new Field("TMID","StuPlanTerm","TMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","StuPlanTerm","Source");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","StuPlanTerm","State");
		}
		#endregion


	}
}

