//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类StuRegistAA 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("StuRegistAA")]
	[Serializable]
	public partial class StuRegistAA : Entity 
	{
		#region Model
		private int _SRGID;
		private string _Yearname;
		private int? _Atyid;
		private int? _Stdid;
		private string _PMState;
		private string _RGState;
		private DateTime? _RGdate;
		private string _RGIP;
		private string _RGOper;
		/// <summary>
		/// 
		/// </summary>
		public int SRGID
		{
			get{ return _SRGID; }
			set
			{
				this.OnPropertyValueChange(_.SRGID,_SRGID,value);
				this._SRGID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Yearname
		{
			get{ return _Yearname; }
			set
			{
				this.OnPropertyValueChange(_.Yearname,_Yearname,value);
				this._Yearname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Atyid
		{
			get{ return _Atyid; }
			set
			{
				this.OnPropertyValueChange(_.Atyid,_Atyid,value);
				this._Atyid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PMState
		{
			get{ return _PMState; }
			set
			{
				this.OnPropertyValueChange(_.PMState,_PMState,value);
				this._PMState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RGState
		{
			get{ return _RGState; }
			set
			{
				this.OnPropertyValueChange(_.RGState,_RGState,value);
				this._RGState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? RGdate
		{
			get{ return _RGdate; }
			set
			{
				this.OnPropertyValueChange(_.RGdate,_RGdate,value);
				this._RGdate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RGIP
		{
			get{ return _RGIP; }
			set
			{
				this.OnPropertyValueChange(_.RGIP,_RGIP,value);
				this._RGIP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RGOper
		{
			get{ return _RGOper; }
			set
			{
				this.OnPropertyValueChange(_.RGOper,_RGOper,value);
				this._RGOper=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SRGID,
				_.Yearname,
				_.Atyid,
				_.Stdid,
				_.PMState,
				_.RGState,
				_.RGdate,
				_.RGIP,
				_.RGOper};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SRGID,
				this._Yearname,
				this._Atyid,
				this._Stdid,
				this._PMState,
				this._RGState,
				this._RGdate,
				this._RGIP,
				this._RGOper};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","StuRegistAA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SRGID = new Field("SRGID","StuRegistAA","SRGID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Yearname = new Field("Yearname","StuRegistAA","Yearname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atyid = new Field("atyid","StuRegistAA","atyid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("stdid","StuRegistAA","stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PMState = new Field("PMState","StuRegistAA","PMState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RGState = new Field("RGState","StuRegistAA","RGState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RGdate = new Field("RGdate","StuRegistAA","RGdate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RGIP = new Field("RGIP","StuRegistAA","RGIP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RGOper = new Field("RGOper","StuRegistAA","RGOper");
		}
		#endregion


	}
}

