//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类Stureportold 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("stureportold")]
	[Serializable]
	public partial class Stureportold : Entity 
	{
		#region Model
		private int _SRID;
		private string _Examine;
		private int? _CCID;
		private int? _Stuid;
		private string _Trueresult;
		private decimal? _Truepoint;
		/// <summary>
		/// 
		/// </summary>
		public int SRID
		{
			get{ return _SRID; }
			set
			{
				this.OnPropertyValueChange(_.SRID,_SRID,value);
				this._SRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Examine
		{
			get{ return _Examine; }
			set
			{
				this.OnPropertyValueChange(_.Examine,_Examine,value);
				this._Examine=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stuid
		{
			get{ return _Stuid; }
			set
			{
				this.OnPropertyValueChange(_.Stuid,_Stuid,value);
				this._Stuid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Trueresult
		{
			get{ return _Trueresult; }
			set
			{
				this.OnPropertyValueChange(_.Trueresult,_Trueresult,value);
				this._Trueresult=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Truepoint
		{
			get{ return _Truepoint; }
			set
			{
				this.OnPropertyValueChange(_.Truepoint,_Truepoint,value);
				this._Truepoint=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.SRID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SRID,
				_.Examine,
				_.CCID,
				_.Stuid,
				_.Trueresult,
				_.Truepoint};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SRID,
				this._Examine,
				this._CCID,
				this._Stuid,
				this._Trueresult,
				this._Truepoint};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","stureportold");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SRID = new Field("SRID","stureportold","SRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Examine = new Field("examine","stureportold","examine");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","stureportold","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stuid = new Field("stuid","stureportold","stuid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Trueresult = new Field("trueresult","stureportold","trueresult");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Truepoint = new Field("truepoint","stureportold","truepoint");
		}
		#endregion


	}
}

