//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ThesisStu 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ThesisStu")]
	[Serializable]
	public partial class ThesisStu : Entity 
	{
		#region Model
		private int _THDID;
		private int? _THID;
		private int? _StuID;
		private string _PSID;
		private string _Title;
		private string _MayorRequest;
		private string _State;
		private DateTime? _Mdate;
		private int? _YearName;
		private string _Atstate;
		private string _Schedule;
		private string _Prospectus;
		private DateTime? _Taskdate;
		/// <summary>
		/// 
		/// </summary>
		public int THDID
		{
			get{ return _THDID; }
			set
			{
				this.OnPropertyValueChange(_.THDID,_THDID,value);
				this._THDID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? THID
		{
			get{ return _THID; }
			set
			{
				this.OnPropertyValueChange(_.THID,_THID,value);
				this._THID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? StuID
		{
			get{ return _StuID; }
			set
			{
				this.OnPropertyValueChange(_.StuID,_StuID,value);
				this._StuID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MayorRequest
		{
			get{ return _MayorRequest; }
			set
			{
				this.OnPropertyValueChange(_.MayorRequest,_MayorRequest,value);
				this._MayorRequest=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Mdate
		{
			get{ return _Mdate; }
			set
			{
				this.OnPropertyValueChange(_.Mdate,_Mdate,value);
				this._Mdate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? YearName
		{
			get{ return _YearName; }
			set
			{
				this.OnPropertyValueChange(_.YearName,_YearName,value);
				this._YearName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Atstate
		{
			get{ return _Atstate; }
			set
			{
				this.OnPropertyValueChange(_.Atstate,_Atstate,value);
				this._Atstate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Schedule
		{
			get{ return _Schedule; }
			set
			{
				this.OnPropertyValueChange(_.Schedule,_Schedule,value);
				this._Schedule=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Prospectus
		{
			get{ return _Prospectus; }
			set
			{
				this.OnPropertyValueChange(_.Prospectus,_Prospectus,value);
				this._Prospectus=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Taskdate
		{
			get{ return _Taskdate; }
			set
			{
				this.OnPropertyValueChange(_.Taskdate,_Taskdate,value);
				this._Taskdate=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.THDID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.THDID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.THDID,
				_.THID,
				_.StuID,
				_.PSID,
				_.Title,
				_.MayorRequest,
				_.State,
				_.Mdate,
				_.YearName,
				_.Atstate,
				_.Schedule,
				_.Prospectus,
				_.Taskdate};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._THDID,
				this._THID,
				this._StuID,
				this._PSID,
				this._Title,
				this._MayorRequest,
				this._State,
				this._Mdate,
				this._YearName,
				this._Atstate,
				this._Schedule,
				this._Prospectus,
				this._Taskdate};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ThesisStu");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field THDID = new Field("THDID","ThesisStu","THDID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field THID = new Field("THID","ThesisStu","THID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuID = new Field("StuID","ThesisStu","StuID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","ThesisStu","PSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("title","ThesisStu","title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MayorRequest = new Field("MayorRequest","ThesisStu","MayorRequest");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","ThesisStu","state");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Mdate = new Field("Mdate","ThesisStu","Mdate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field YearName = new Field("YearName","ThesisStu","YearName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atstate = new Field("atstate","ThesisStu","atstate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Schedule = new Field("Schedule","ThesisStu","Schedule");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Prospectus = new Field("Prospectus","ThesisStu","Prospectus");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Taskdate = new Field("taskdate","ThesisStu","taskdate");
		}
		#endregion


	}
}

