//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类ThesisType 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ThesisType")]
	[Serializable]
	public partial class ThesisType : Entity 
	{
		#region Model
		private int _TypeID;
		private string _TypeName;
		/// <summary>
		/// 
		/// </summary>
		public int TypeID
		{
			get{ return _TypeID; }
			set
			{
				this.OnPropertyValueChange(_.TypeID,_TypeID,value);
				this._TypeID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TypeName
		{
			get{ return _TypeName; }
			set
			{
				this.OnPropertyValueChange(_.TypeName,_TypeName,value);
				this._TypeName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.TypeID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.TypeID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TypeID,
				_.TypeName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TypeID,
				this._TypeName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ThesisType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeID = new Field("TypeID","ThesisType","TypeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName","ThesisType","TypeName");
		}
		#endregion


	}
}

