//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_AppraiseD 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_AppraiseD")]
	[Serializable]
	public partial class vw_AppraiseD : Entity 
	{
		#region Model
		private int _APDID;
		private int? _APMID;
		private int? _XH;
		private string _Sort;
		private string _ContentA;
		private decimal? _SA;
		private decimal? _SB;
		private decimal? _SC;
		private decimal? _SD;
		private string _State;
		private decimal? _SE;
		private string _StateM;
		private string _CSortCode;
		private string _StandA;
		private string _StandC;
		private string _Stype;
		/// <summary>
		/// 
		/// </summary>
		public int APDID
		{
			get{ return _APDID; }
			set
			{
				this.OnPropertyValueChange(_.APDID,_APDID,value);
				this._APDID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? APMID
		{
			get{ return _APMID; }
			set
			{
				this.OnPropertyValueChange(_.APMID,_APMID,value);
				this._APMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? XH
		{
			get{ return _XH; }
			set
			{
				this.OnPropertyValueChange(_.XH,_XH,value);
				this._XH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ContentA
		{
			get{ return _ContentA; }
			set
			{
				this.OnPropertyValueChange(_.ContentA,_ContentA,value);
				this._ContentA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SA
		{
			get{ return _SA; }
			set
			{
				this.OnPropertyValueChange(_.SA,_SA,value);
				this._SA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SB
		{
			get{ return _SB; }
			set
			{
				this.OnPropertyValueChange(_.SB,_SB,value);
				this._SB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SC
		{
			get{ return _SC; }
			set
			{
				this.OnPropertyValueChange(_.SC,_SC,value);
				this._SC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SD
		{
			get{ return _SD; }
			set
			{
				this.OnPropertyValueChange(_.SD,_SD,value);
				this._SD=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SE
		{
			get{ return _SE; }
			set
			{
				this.OnPropertyValueChange(_.SE,_SE,value);
				this._SE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StateM
		{
			get{ return _StateM; }
			set
			{
				this.OnPropertyValueChange(_.StateM,_StateM,value);
				this._StateM=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CSortCode
		{
			get{ return _CSortCode; }
			set
			{
				this.OnPropertyValueChange(_.CSortCode,_CSortCode,value);
				this._CSortCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StandA
		{
			get{ return _StandA; }
			set
			{
				this.OnPropertyValueChange(_.StandA,_StandA,value);
				this._StandA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StandC
		{
			get{ return _StandC; }
			set
			{
				this.OnPropertyValueChange(_.StandC,_StandC,value);
				this._StandC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Stype
		{
			get{ return _Stype; }
			set
			{
				this.OnPropertyValueChange(_.Stype,_Stype,value);
				this._Stype=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.APDID,
				_.APMID,
				_.XH,
				_.Sort,
				_.ContentA,
				_.SA,
				_.SB,
				_.SC,
				_.SD,
				_.State,
				_.SE,
				_.StateM,
				_.CSortCode,
				_.StandA,
				_.StandC,
				_.Stype};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._APDID,
				this._APMID,
				this._XH,
				this._Sort,
				this._ContentA,
				this._SA,
				this._SB,
				this._SC,
				this._SD,
				this._State,
				this._SE,
				this._StateM,
				this._CSortCode,
				this._StandA,
				this._StandC,
				this._Stype};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_AppraiseD");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APDID = new Field("APDID","vw_AppraiseD","APDID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field APMID = new Field("APMID","vw_AppraiseD","APMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field XH = new Field("XH","vw_AppraiseD","XH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sort = new Field("Sort","vw_AppraiseD","Sort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ContentA = new Field("ContentA","vw_AppraiseD","ContentA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SA = new Field("SA","vw_AppraiseD","SA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SB = new Field("SB","vw_AppraiseD","SB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SC = new Field("SC","vw_AppraiseD","SC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SD = new Field("SD","vw_AppraiseD","SD");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","vw_AppraiseD","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SE = new Field("SE","vw_AppraiseD","SE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StateM = new Field("StateM","vw_AppraiseD","StateM");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CSortCode = new Field("CSortCode","vw_AppraiseD","CSortCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StandA = new Field("StandA","vw_AppraiseD","StandA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StandC = new Field("StandC","vw_AppraiseD","StandC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stype = new Field("Stype","vw_AppraiseD","Stype");
		}
		#endregion


	}
}

