//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_ChatMember 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_ChatMember")]
	[Serializable]
	public partial class vw_ChatMember : Entity 
	{
		#region Model
		private string _CMname;
		private string _Username;
		private int? _CMID;
		private int? _CRID;
		private DateTime? _CDate;
		private string _State;
		private int _CMBID;
		private string _Builder;
		private string _RoomState;
		/// <summary>
		/// 
		/// </summary>
		public string CMname
		{
			get{ return _CMname; }
			set
			{
				this.OnPropertyValueChange(_.CMname,_CMname,value);
				this._CMname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Username
		{
			get{ return _Username; }
			set
			{
				this.OnPropertyValueChange(_.Username,_Username,value);
				this._Username=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CMID
		{
			get{ return _CMID; }
			set
			{
				this.OnPropertyValueChange(_.CMID,_CMID,value);
				this._CMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CRID
		{
			get{ return _CRID; }
			set
			{
				this.OnPropertyValueChange(_.CRID,_CRID,value);
				this._CRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CDate
		{
			get{ return _CDate; }
			set
			{
				this.OnPropertyValueChange(_.CDate,_CDate,value);
				this._CDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int CMBID
		{
			get{ return _CMBID; }
			set
			{
				this.OnPropertyValueChange(_.CMBID,_CMBID,value);
				this._CMBID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Builder
		{
			get{ return _Builder; }
			set
			{
				this.OnPropertyValueChange(_.Builder,_Builder,value);
				this._Builder=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RoomState
		{
			get{ return _RoomState; }
			set
			{
				this.OnPropertyValueChange(_.RoomState,_RoomState,value);
				this._RoomState=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CMname,
				_.Username,
				_.CMID,
				_.CRID,
				_.CDate,
				_.State,
				_.CMBID,
				_.Builder,
				_.RoomState};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CMname,
				this._Username,
				this._CMID,
				this._CRID,
				this._CDate,
				this._State,
				this._CMBID,
				this._Builder,
				this._RoomState};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_ChatMember");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMname = new Field("CMname","vw_ChatMember","CMname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Username = new Field("Username","vw_ChatMember","Username");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMID = new Field("CMID","vw_ChatMember","CMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRID = new Field("CRID","vw_ChatMember","CRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CDate = new Field("CDate","vw_ChatMember","CDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","vw_ChatMember","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMBID = new Field("CMBID","vw_ChatMember","CMBID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Builder = new Field("Builder","vw_ChatMember","Builder");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoomState = new Field("RoomState","vw_ChatMember","RoomState");
		}
		#endregion


	}
}

