//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_Personal 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_Personal")]
	[Serializable]
	public partial class vw_Personal : Entity 
	{
		#region Model
		private string _PsName;
		private int _TUID;
		private int? _TRoleID;
		private int? _PSID;
		/// <summary>
		/// 
		/// </summary>
		public string PsName
		{
			get{ return _PsName; }
			set
			{
				this.OnPropertyValueChange(_.PsName,_PsName,value);
				this._PsName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int TUID
		{
			get{ return _TUID; }
			set
			{
				this.OnPropertyValueChange(_.TUID,_TUID,value);
				this._TUID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TRoleID
		{
			get{ return _TRoleID; }
			set
			{
				this.OnPropertyValueChange(_.TRoleID,_TRoleID,value);
				this._TRoleID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PsName,
				_.TUID,
				_.TRoleID,
				_.PSID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PsName,
				this._TUID,
				this._TRoleID,
				this._PSID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_Personal");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PsName = new Field("PsName","vw_Personal","PsName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TUID = new Field("TUID","vw_Personal","TUID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRoleID = new Field("TRoleID","vw_Personal","TRoleID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","vw_Personal","PSID");
		}
		#endregion


	}
}

