//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_PJ_File 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_PJ_File")]
	[Serializable]
	public partial class vw_PJ_File : Entity 
	{
		#region Model
		private int _PFID;
		private int? _FMID;
		private int? _SubjID;
		private string _MFilename;
		private DateTime? _Indate;
		private string _FromDept;
		private string _FName;
		private string _Oper;
		/// <summary>
		/// 
		/// </summary>
		public int PFID
		{
			get{ return _PFID; }
			set
			{
				this.OnPropertyValueChange(_.PFID,_PFID,value);
				this._PFID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? FMID
		{
			get{ return _FMID; }
			set
			{
				this.OnPropertyValueChange(_.FMID,_FMID,value);
				this._FMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SubjID
		{
			get{ return _SubjID; }
			set
			{
				this.OnPropertyValueChange(_.SubjID,_SubjID,value);
				this._SubjID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MFilename
		{
			get{ return _MFilename; }
			set
			{
				this.OnPropertyValueChange(_.MFilename,_MFilename,value);
				this._MFilename=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Indate
		{
			get{ return _Indate; }
			set
			{
				this.OnPropertyValueChange(_.Indate,_Indate,value);
				this._Indate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FromDept
		{
			get{ return _FromDept; }
			set
			{
				this.OnPropertyValueChange(_.FromDept,_FromDept,value);
				this._FromDept=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FName
		{
			get{ return _FName; }
			set
			{
				this.OnPropertyValueChange(_.FName,_FName,value);
				this._FName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Oper
		{
			get{ return _Oper; }
			set
			{
				this.OnPropertyValueChange(_.Oper,_Oper,value);
				this._Oper=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PFID,
				_.FMID,
				_.SubjID,
				_.MFilename,
				_.Indate,
				_.FromDept,
				_.FName,
				_.Oper};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._PFID,
				this._FMID,
				this._SubjID,
				this._MFilename,
				this._Indate,
				this._FromDept,
				this._FName,
				this._Oper};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_PJ_File");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PFID = new Field("PFID","vw_PJ_File","PFID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FMID = new Field("FMID","vw_PJ_File","FMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjID = new Field("SubjID","vw_PJ_File","SubjID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MFilename = new Field("MFilename","vw_PJ_File","MFilename");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Indate = new Field("Indate","vw_PJ_File","Indate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FromDept = new Field("FromDept","vw_PJ_File","FromDept");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FName = new Field("FName","vw_PJ_File","FName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Oper = new Field("Oper","vw_PJ_File","Oper");
		}
		#endregion


	}
}

