//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_StatByTeacher 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_StatByTeacher")]
	[Serializable]
	public partial class vw_StatByTeacher : Entity 
	{
		#region Model
		private string _CCode;
		private string _CCname;
		private int? _AtyID;
		private int? _CCID;
		private int? _PSID;
		private int? _LevID;
		private string _LevContent;
		private int? _FromL;
		private int? _ToL;
		private int? _PSNum;
		private int? _AllNum;
		private decimal? _Per;
		private decimal? _Avgs;
		private decimal? _MaxS;
		private decimal? _MinS;
		private decimal? _GoodPer;
		private decimal? _BadPer;
		private string _PsName;
		/// <summary>
		/// 
		/// </summary>
		public string CCode
		{
			get{ return _CCode; }
			set
			{
				this.OnPropertyValueChange(_.CCode,_CCode,value);
				this._CCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CCname
		{
			get{ return _CCname; }
			set
			{
				this.OnPropertyValueChange(_.CCname,_CCname,value);
				this._CCname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AtyID
		{
			get{ return _AtyID; }
			set
			{
				this.OnPropertyValueChange(_.AtyID,_AtyID,value);
				this._AtyID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LevID
		{
			get{ return _LevID; }
			set
			{
				this.OnPropertyValueChange(_.LevID,_LevID,value);
				this._LevID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LevContent
		{
			get{ return _LevContent; }
			set
			{
				this.OnPropertyValueChange(_.LevContent,_LevContent,value);
				this._LevContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? FromL
		{
			get{ return _FromL; }
			set
			{
				this.OnPropertyValueChange(_.FromL,_FromL,value);
				this._FromL=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ToL
		{
			get{ return _ToL; }
			set
			{
				this.OnPropertyValueChange(_.ToL,_ToL,value);
				this._ToL=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSNum
		{
			get{ return _PSNum; }
			set
			{
				this.OnPropertyValueChange(_.PSNum,_PSNum,value);
				this._PSNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AllNum
		{
			get{ return _AllNum; }
			set
			{
				this.OnPropertyValueChange(_.AllNum,_AllNum,value);
				this._AllNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Per
		{
			get{ return _Per; }
			set
			{
				this.OnPropertyValueChange(_.Per,_Per,value);
				this._Per=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Avgs
		{
			get{ return _Avgs; }
			set
			{
				this.OnPropertyValueChange(_.Avgs,_Avgs,value);
				this._Avgs=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? MaxS
		{
			get{ return _MaxS; }
			set
			{
				this.OnPropertyValueChange(_.MaxS,_MaxS,value);
				this._MaxS=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? MinS
		{
			get{ return _MinS; }
			set
			{
				this.OnPropertyValueChange(_.MinS,_MinS,value);
				this._MinS=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? GoodPer
		{
			get{ return _GoodPer; }
			set
			{
				this.OnPropertyValueChange(_.GoodPer,_GoodPer,value);
				this._GoodPer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? BadPer
		{
			get{ return _BadPer; }
			set
			{
				this.OnPropertyValueChange(_.BadPer,_BadPer,value);
				this._BadPer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PsName
		{
			get{ return _PsName; }
			set
			{
				this.OnPropertyValueChange(_.PsName,_PsName,value);
				this._PsName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CCode,
				_.CCname,
				_.AtyID,
				_.CCID,
				_.PSID,
				_.LevID,
				_.LevContent,
				_.FromL,
				_.ToL,
				_.PSNum,
				_.AllNum,
				_.Per,
				_.Avgs,
				_.MaxS,
				_.MinS,
				_.GoodPer,
				_.BadPer,
				_.PsName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CCode,
				this._CCname,
				this._AtyID,
				this._CCID,
				this._PSID,
				this._LevID,
				this._LevContent,
				this._FromL,
				this._ToL,
				this._PSNum,
				this._AllNum,
				this._Per,
				this._Avgs,
				this._MaxS,
				this._MinS,
				this._GoodPer,
				this._BadPer,
				this._PsName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_StatByTeacher");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCode = new Field("CCode","vw_StatByTeacher","CCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCname = new Field("CCname","vw_StatByTeacher","CCname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AtyID = new Field("AtyID","vw_StatByTeacher","AtyID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","vw_StatByTeacher","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","vw_StatByTeacher","PSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LevID = new Field("LevID","vw_StatByTeacher","LevID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LevContent = new Field("LevContent","vw_StatByTeacher","LevContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FromL = new Field("FromL","vw_StatByTeacher","FromL");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ToL = new Field("ToL","vw_StatByTeacher","ToL");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSNum = new Field("PSNum","vw_StatByTeacher","PSNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllNum = new Field("AllNum","vw_StatByTeacher","AllNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Per = new Field("Per","vw_StatByTeacher","Per");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Avgs = new Field("Avgs","vw_StatByTeacher","Avgs");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MaxS = new Field("MaxS","vw_StatByTeacher","MaxS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MinS = new Field("MinS","vw_StatByTeacher","MinS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GoodPer = new Field("GoodPer","vw_StatByTeacher","GoodPer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BadPer = new Field("BadPer","vw_StatByTeacher","BadPer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PsName = new Field("PsName","vw_StatByTeacher","PsName");
		}
		#endregion


	}
}

