//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_Stureport_Main_max_2 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_Stureport_Main_max_2")]
	[Serializable]
	public partial class vw_Stureport_Main_max_2 : Entity 
	{
		#region Model
		private decimal? _truepoint;
		private decimal? _Source;
		private int? _CCIDB;
		private int? _StuID;
		private int? _SPID;
		private int? _Grid;
		/// <summary>
		/// 
		/// </summary>
		public decimal? truepoint
		{
			get{ return _truepoint; }
			set
			{
				this.OnPropertyValueChange(_.truepoint,_truepoint,value);
				this._truepoint=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCIDB
		{
			get{ return _CCIDB; }
			set
			{
				this.OnPropertyValueChange(_.CCIDB,_CCIDB,value);
				this._CCIDB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? StuID
		{
			get{ return _StuID; }
			set
			{
				this.OnPropertyValueChange(_.StuID,_StuID,value);
				this._StuID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SPID
		{
			get{ return _SPID; }
			set
			{
				this.OnPropertyValueChange(_.SPID,_SPID,value);
				this._SPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Grid
		{
			get{ return _Grid; }
			set
			{
				this.OnPropertyValueChange(_.Grid,_Grid,value);
				this._Grid=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.truepoint,
				_.Source,
				_.CCIDB,
				_.StuID,
				_.SPID,
				_.Grid};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._truepoint,
				this._Source,
				this._CCIDB,
				this._StuID,
				this._SPID,
				this._Grid};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_Stureport_Main_max_2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field truepoint = new Field("truepoint","vw_Stureport_Main_max_2","truepoint");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","vw_Stureport_Main_max_2","Source");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCIDB = new Field("CCIDB","vw_Stureport_Main_max_2","CCIDB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuID = new Field("StuID","vw_Stureport_Main_max_2","StuID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPID = new Field("SPID","vw_Stureport_Main_max_2","SPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Grid = new Field("Grid","vw_Stureport_Main_max_2","Grid");
		}
		#endregion


	}
}

