//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_StuReportMa 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_StuReportMa")]
	[Serializable]
	public partial class vw_StuReportMa : Entity 
	{
		#region Model
		private int _TCID;
		private string _教学班级名称;
		private string _课程名称;
		private string _编码;
		private string _任课教师;
		private string _助课教师;
		private string _状态;
		private string _当前学期;
		private int? _预计数量;
		private decimal? _学分;
		private int? _ActYear;
		private string _考试类型;
		private string _DeptName;
		private string _ReportState;
		private string _Affirmant;
		private int? _MaxStuNum;
		private int? _CCID;
		/// <summary>
		/// 
		/// </summary>
		public int TCID
		{
			get{ return _TCID; }
			set
			{
				this.OnPropertyValueChange(_.TCID,_TCID,value);
				this._TCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 教学班级名称
		{
			get{ return _教学班级名称; }
			set
			{
				this.OnPropertyValueChange(_.教学班级名称,_教学班级名称,value);
				this._教学班级名称=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 课程名称
		{
			get{ return _课程名称; }
			set
			{
				this.OnPropertyValueChange(_.课程名称,_课程名称,value);
				this._课程名称=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 编码
		{
			get{ return _编码; }
			set
			{
				this.OnPropertyValueChange(_.编码,_编码,value);
				this._编码=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 任课教师
		{
			get{ return _任课教师; }
			set
			{
				this.OnPropertyValueChange(_.任课教师,_任课教师,value);
				this._任课教师=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 助课教师
		{
			get{ return _助课教师; }
			set
			{
				this.OnPropertyValueChange(_.助课教师,_助课教师,value);
				this._助课教师=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 状态
		{
			get{ return _状态; }
			set
			{
				this.OnPropertyValueChange(_.状态,_状态,value);
				this._状态=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 当前学期
		{
			get{ return _当前学期; }
			set
			{
				this.OnPropertyValueChange(_.当前学期,_当前学期,value);
				this._当前学期=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? 预计数量
		{
			get{ return _预计数量; }
			set
			{
				this.OnPropertyValueChange(_.预计数量,_预计数量,value);
				this._预计数量=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? 学分
		{
			get{ return _学分; }
			set
			{
				this.OnPropertyValueChange(_.学分,_学分,value);
				this._学分=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ActYear
		{
			get{ return _ActYear; }
			set
			{
				this.OnPropertyValueChange(_.ActYear,_ActYear,value);
				this._ActYear=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 考试类型
		{
			get{ return _考试类型; }
			set
			{
				this.OnPropertyValueChange(_.考试类型,_考试类型,value);
				this._考试类型=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange(_.DeptName,_DeptName,value);
				this._DeptName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ReportState
		{
			get{ return _ReportState; }
			set
			{
				this.OnPropertyValueChange(_.ReportState,_ReportState,value);
				this._ReportState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Affirmant
		{
			get{ return _Affirmant; }
			set
			{
				this.OnPropertyValueChange(_.Affirmant,_Affirmant,value);
				this._Affirmant=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MaxStuNum
		{
			get{ return _MaxStuNum; }
			set
			{
				this.OnPropertyValueChange(_.MaxStuNum,_MaxStuNum,value);
				this._MaxStuNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TCID,
				_.教学班级名称,
				_.课程名称,
				_.编码,
				_.任课教师,
				_.助课教师,
				_.状态,
				_.当前学期,
				_.预计数量,
				_.学分,
				_.ActYear,
				_.考试类型,
				_.DeptName,
				_.ReportState,
				_.Affirmant,
				_.MaxStuNum,
				_.CCID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TCID,
				this._教学班级名称,
				this._课程名称,
				this._编码,
				this._任课教师,
				this._助课教师,
				this._状态,
				this._当前学期,
				this._预计数量,
				this._学分,
				this._ActYear,
				this._考试类型,
				this._DeptName,
				this._ReportState,
				this._Affirmant,
				this._MaxStuNum,
				this._CCID};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_StuReportMa");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TCID = new Field("TCID","vw_StuReportMa","TCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 教学班级名称 = new Field("教学班级名称","vw_StuReportMa","教学班级名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 课程名称 = new Field("课程名称","vw_StuReportMa","课程名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 编码 = new Field("编码","vw_StuReportMa","编码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 任课教师 = new Field("任课教师","vw_StuReportMa","任课教师");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 助课教师 = new Field("助课教师","vw_StuReportMa","助课教师");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 状态 = new Field("状态","vw_StuReportMa","状态");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 当前学期 = new Field("当前学期","vw_StuReportMa","当前学期");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 预计数量 = new Field("预计数量","vw_StuReportMa","预计数量");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学分 = new Field("学分","vw_StuReportMa","学分");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ActYear = new Field("ActYear","vw_StuReportMa","ActYear");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 考试类型 = new Field("考试类型","vw_StuReportMa","考试类型");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName","vw_StuReportMa","DeptName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReportState = new Field("ReportState","vw_StuReportMa","ReportState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Affirmant = new Field("Affirmant","vw_StuReportMa","Affirmant");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MaxStuNum = new Field("MaxStuNum","vw_StuReportMa","MaxStuNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","vw_StuReportMa","CCID");
		}
		#endregion


	}
}

