//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_StuAnswerTest 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_StuAnswerTest")]
	[Serializable]
	public partial class vw_StuAnswerTest : Entity 
	{
		#region Model
		private string _SBName;
		private string _TestQuestion;
		private string _TestKey;
		private int _ASID;
		private int? _StuID;
		private int? _CCID;
		private int? _TSID;
		private string _Answer;
		private string _ASDate;
		private int? _ASNO;
		private string _StdName;
		private string _CHPNO;
		private int? _CHPID;
		private string _ChpName;
		private string _ASState;
		private int? _ATYID;
		private string _SBID;
		private int? _Score;
		private string _StdCode;
		/// <summary>
		/// 
		/// </summary>
		public string SBName
		{
			get{ return _SBName; }
			set
			{
				this.OnPropertyValueChange(_.SBName,_SBName,value);
				this._SBName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TestQuestion
		{
			get{ return _TestQuestion; }
			set
			{
				this.OnPropertyValueChange(_.TestQuestion,_TestQuestion,value);
				this._TestQuestion=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TestKey
		{
			get{ return _TestKey; }
			set
			{
				this.OnPropertyValueChange(_.TestKey,_TestKey,value);
				this._TestKey=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ASID
		{
			get{ return _ASID; }
			set
			{
				this.OnPropertyValueChange(_.ASID,_ASID,value);
				this._ASID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? StuID
		{
			get{ return _StuID; }
			set
			{
				this.OnPropertyValueChange(_.StuID,_StuID,value);
				this._StuID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TSID
		{
			get{ return _TSID; }
			set
			{
				this.OnPropertyValueChange(_.TSID,_TSID,value);
				this._TSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Answer
		{
			get{ return _Answer; }
			set
			{
				this.OnPropertyValueChange(_.Answer,_Answer,value);
				this._Answer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ASDate
		{
			get{ return _ASDate; }
			set
			{
				this.OnPropertyValueChange(_.ASDate,_ASDate,value);
				this._ASDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ASNO
		{
			get{ return _ASNO; }
			set
			{
				this.OnPropertyValueChange(_.ASNO,_ASNO,value);
				this._ASNO=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdName
		{
			get{ return _StdName; }
			set
			{
				this.OnPropertyValueChange(_.StdName,_StdName,value);
				this._StdName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CHPNO
		{
			get{ return _CHPNO; }
			set
			{
				this.OnPropertyValueChange(_.CHPNO,_CHPNO,value);
				this._CHPNO=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CHPID
		{
			get{ return _CHPID; }
			set
			{
				this.OnPropertyValueChange(_.CHPID,_CHPID,value);
				this._CHPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ChpName
		{
			get{ return _ChpName; }
			set
			{
				this.OnPropertyValueChange(_.ChpName,_ChpName,value);
				this._ChpName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ASState
		{
			get{ return _ASState; }
			set
			{
				this.OnPropertyValueChange(_.ASState,_ASState,value);
				this._ASState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATYID
		{
			get{ return _ATYID; }
			set
			{
				this.OnPropertyValueChange(_.ATYID,_ATYID,value);
				this._ATYID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SBID
		{
			get{ return _SBID; }
			set
			{
				this.OnPropertyValueChange(_.SBID,_SBID,value);
				this._SBID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdCode
		{
			get{ return _StdCode; }
			set
			{
				this.OnPropertyValueChange(_.StdCode,_StdCode,value);
				this._StdCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.SBName,
				_.TestQuestion,
				_.TestKey,
				_.ASID,
				_.StuID,
				_.CCID,
				_.TSID,
				_.Answer,
				_.ASDate,
				_.ASNO,
				_.StdName,
				_.CHPNO,
				_.CHPID,
				_.ChpName,
				_.ASState,
				_.ATYID,
				_.SBID,
				_.Score,
				_.StdCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._SBName,
				this._TestQuestion,
				this._TestKey,
				this._ASID,
				this._StuID,
				this._CCID,
				this._TSID,
				this._Answer,
				this._ASDate,
				this._ASNO,
				this._StdName,
				this._CHPNO,
				this._CHPID,
				this._ChpName,
				this._ASState,
				this._ATYID,
				this._SBID,
				this._Score,
				this._StdCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_StuAnswerTest");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SBName = new Field("SBName","vw_StuAnswerTest","SBName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TestQuestion = new Field("TestQuestion","vw_StuAnswerTest","TestQuestion");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TestKey = new Field("TestKey","vw_StuAnswerTest","TestKey");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ASID = new Field("ASID","vw_StuAnswerTest","ASID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuID = new Field("StuID","vw_StuAnswerTest","StuID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","vw_StuAnswerTest","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TSID = new Field("TSID","vw_StuAnswerTest","TSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Answer = new Field("Answer","vw_StuAnswerTest","Answer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ASDate = new Field("ASDate","vw_StuAnswerTest","ASDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ASNO = new Field("ASNO","vw_StuAnswerTest","ASNO");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdName = new Field("StdName","vw_StuAnswerTest","StdName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CHPNO = new Field("CHPNO","vw_StuAnswerTest","CHPNO");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CHPID = new Field("CHPID","vw_StuAnswerTest","CHPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChpName = new Field("ChpName","vw_StuAnswerTest","ChpName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ASState = new Field("ASState","vw_StuAnswerTest","ASState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATYID = new Field("ATYID","vw_StuAnswerTest","ATYID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SBID = new Field("SBID","vw_StuAnswerTest","SBID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","vw_StuAnswerTest","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdCode = new Field("StdCode","vw_StuAnswerTest","StdCode");
		}
		#endregion


	}
}

