//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_StuReport 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_StuReport")]
	[Serializable]
	public partial class vw_StuReport : Entity 
	{
		#region Model
		private decimal? _学绩分;
		private decimal? _绩点;
		private string _备注;
		private string _成绩;
		private string _Exam;
		private string _Normal;
		private string _实验;
		private string _TrueResult;
		private decimal? _TruePoint;
		private int? _ECID;
		private int? _EPID;
		private int? _CLID;
		private int? _SPID;
		private int _SRID;
		private int? _StuID;
		private string _State;
		private int? _TCID;
		private string _Discipline;
		private string _学号;
		private string _系部;
		private string _班级;
		private string _学生姓名;
		private string _教学班级名称;
		private string _课程名称;
		private string _CCnameEng;
		private decimal? _学分;
		private string _任课教师;
		private string _当前学期;
		private int? _ATYID;
		private string _Minor;
		private int? _SequID;
		private int? _DeptID;
		private int? _GradeID;
		private int? _CLassID;
		private string _DeptCode;
		private int? _PSID;
		private string _ReportState;
		private int? _IFOK;
		private int? _Lev;
		private string _Oper;
		private int? _TotalNum;
		private string _IsMain;
		private int? _ATNo;
		private string _MState;
		private string _PJState;
		private string _CCode;
		private int? _Grid;
		private string _PayMoneyState;
		private string _stdstate;
		private string _GRName;
		private int? _TMID;
		private int? _CCID;
		private string _IFCheck;
		private string _InPlan;
		private string _IFCheckBY;
		private decimal? _ExamNum;
		private string _Csort;
		private string _Mark;
		private string _Sortname;
		private string _byState;
		private string _PlanSort;
		private int? _EXRID;
		private Guid? _GUID;
		private string _TermName;
		private string _Exp;
		private string _Direct;
		private string _ctype;
		private string _考试类型;
		private DateTime? _SelectDate;
		private int? _CCIDB;
		private string _NeedPJ;
		private string _inSplan;
		private string _SplanMemo;
		private int? _MarkA;
		private string _Cunit;
		private decimal? _Period;
		/// <summary>
		/// 
		/// </summary>
		public decimal? 学绩分
		{
			get{ return _学绩分; }
			set
			{
				this.OnPropertyValueChange(_.学绩分,_学绩分,value);
				this._学绩分=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? 绩点
		{
			get{ return _绩点; }
			set
			{
				this.OnPropertyValueChange(_.绩点,_绩点,value);
				this._绩点=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 备注
		{
			get{ return _备注; }
			set
			{
				this.OnPropertyValueChange(_.备注,_备注,value);
				this._备注=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 成绩
		{
			get{ return _成绩; }
			set
			{
				this.OnPropertyValueChange(_.成绩,_成绩,value);
				this._成绩=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Exam
		{
			get{ return _Exam; }
			set
			{
				this.OnPropertyValueChange(_.Exam,_Exam,value);
				this._Exam=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Normal
		{
			get{ return _Normal; }
			set
			{
				this.OnPropertyValueChange(_.Normal,_Normal,value);
				this._Normal=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 实验
		{
			get{ return _实验; }
			set
			{
				this.OnPropertyValueChange(_.实验,_实验,value);
				this._实验=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TrueResult
		{
			get{ return _TrueResult; }
			set
			{
				this.OnPropertyValueChange(_.TrueResult,_TrueResult,value);
				this._TrueResult=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? TruePoint
		{
			get{ return _TruePoint; }
			set
			{
				this.OnPropertyValueChange(_.TruePoint,_TruePoint,value);
				this._TruePoint=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ECID
		{
			get{ return _ECID; }
			set
			{
				this.OnPropertyValueChange(_.ECID,_ECID,value);
				this._ECID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? EPID
		{
			get{ return _EPID; }
			set
			{
				this.OnPropertyValueChange(_.EPID,_EPID,value);
				this._EPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CLID
		{
			get{ return _CLID; }
			set
			{
				this.OnPropertyValueChange(_.CLID,_CLID,value);
				this._CLID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SPID
		{
			get{ return _SPID; }
			set
			{
				this.OnPropertyValueChange(_.SPID,_SPID,value);
				this._SPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int SRID
		{
			get{ return _SRID; }
			set
			{
				this.OnPropertyValueChange(_.SRID,_SRID,value);
				this._SRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? StuID
		{
			get{ return _StuID; }
			set
			{
				this.OnPropertyValueChange(_.StuID,_StuID,value);
				this._StuID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TCID
		{
			get{ return _TCID; }
			set
			{
				this.OnPropertyValueChange(_.TCID,_TCID,value);
				this._TCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Discipline
		{
			get{ return _Discipline; }
			set
			{
				this.OnPropertyValueChange(_.Discipline,_Discipline,value);
				this._Discipline=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 学号
		{
			get{ return _学号; }
			set
			{
				this.OnPropertyValueChange(_.学号,_学号,value);
				this._学号=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 系部
		{
			get{ return _系部; }
			set
			{
				this.OnPropertyValueChange(_.系部,_系部,value);
				this._系部=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 班级
		{
			get{ return _班级; }
			set
			{
				this.OnPropertyValueChange(_.班级,_班级,value);
				this._班级=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 学生姓名
		{
			get{ return _学生姓名; }
			set
			{
				this.OnPropertyValueChange(_.学生姓名,_学生姓名,value);
				this._学生姓名=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 教学班级名称
		{
			get{ return _教学班级名称; }
			set
			{
				this.OnPropertyValueChange(_.教学班级名称,_教学班级名称,value);
				this._教学班级名称=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 课程名称
		{
			get{ return _课程名称; }
			set
			{
				this.OnPropertyValueChange(_.课程名称,_课程名称,value);
				this._课程名称=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CCnameEng
		{
			get{ return _CCnameEng; }
			set
			{
				this.OnPropertyValueChange(_.CCnameEng,_CCnameEng,value);
				this._CCnameEng=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? 学分
		{
			get{ return _学分; }
			set
			{
				this.OnPropertyValueChange(_.学分,_学分,value);
				this._学分=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 任课教师
		{
			get{ return _任课教师; }
			set
			{
				this.OnPropertyValueChange(_.任课教师,_任课教师,value);
				this._任课教师=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 当前学期
		{
			get{ return _当前学期; }
			set
			{
				this.OnPropertyValueChange(_.当前学期,_当前学期,value);
				this._当前学期=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATYID
		{
			get{ return _ATYID; }
			set
			{
				this.OnPropertyValueChange(_.ATYID,_ATYID,value);
				this._ATYID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Minor
		{
			get{ return _Minor; }
			set
			{
				this.OnPropertyValueChange(_.Minor,_Minor,value);
				this._Minor=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SequID
		{
			get{ return _SequID; }
			set
			{
				this.OnPropertyValueChange(_.SequID,_SequID,value);
				this._SequID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DeptID
		{
			get{ return _DeptID; }
			set
			{
				this.OnPropertyValueChange(_.DeptID,_DeptID,value);
				this._DeptID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GradeID
		{
			get{ return _GradeID; }
			set
			{
				this.OnPropertyValueChange(_.GradeID,_GradeID,value);
				this._GradeID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CLassID
		{
			get{ return _CLassID; }
			set
			{
				this.OnPropertyValueChange(_.CLassID,_CLassID,value);
				this._CLassID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PSID
		{
			get{ return _PSID; }
			set
			{
				this.OnPropertyValueChange(_.PSID,_PSID,value);
				this._PSID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ReportState
		{
			get{ return _ReportState; }
			set
			{
				this.OnPropertyValueChange(_.ReportState,_ReportState,value);
				this._ReportState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IFOK
		{
			get{ return _IFOK; }
			set
			{
				this.OnPropertyValueChange(_.IFOK,_IFOK,value);
				this._IFOK=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Lev
		{
			get{ return _Lev; }
			set
			{
				this.OnPropertyValueChange(_.Lev,_Lev,value);
				this._Lev=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Oper
		{
			get{ return _Oper; }
			set
			{
				this.OnPropertyValueChange(_.Oper,_Oper,value);
				this._Oper=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TotalNum
		{
			get{ return _TotalNum; }
			set
			{
				this.OnPropertyValueChange(_.TotalNum,_TotalNum,value);
				this._TotalNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IsMain
		{
			get{ return _IsMain; }
			set
			{
				this.OnPropertyValueChange(_.IsMain,_IsMain,value);
				this._IsMain=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATNo
		{
			get{ return _ATNo; }
			set
			{
				this.OnPropertyValueChange(_.ATNo,_ATNo,value);
				this._ATNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MState
		{
			get{ return _MState; }
			set
			{
				this.OnPropertyValueChange(_.MState,_MState,value);
				this._MState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PJState
		{
			get{ return _PJState; }
			set
			{
				this.OnPropertyValueChange(_.PJState,_PJState,value);
				this._PJState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CCode
		{
			get{ return _CCode; }
			set
			{
				this.OnPropertyValueChange(_.CCode,_CCode,value);
				this._CCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Grid
		{
			get{ return _Grid; }
			set
			{
				this.OnPropertyValueChange(_.Grid,_Grid,value);
				this._Grid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PayMoneyState
		{
			get{ return _PayMoneyState; }
			set
			{
				this.OnPropertyValueChange(_.PayMoneyState,_PayMoneyState,value);
				this._PayMoneyState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string stdstate
		{
			get{ return _stdstate; }
			set
			{
				this.OnPropertyValueChange(_.stdstate,_stdstate,value);
				this._stdstate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GRName
		{
			get{ return _GRName; }
			set
			{
				this.OnPropertyValueChange(_.GRName,_GRName,value);
				this._GRName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TMID
		{
			get{ return _TMID; }
			set
			{
				this.OnPropertyValueChange(_.TMID,_TMID,value);
				this._TMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCID
		{
			get{ return _CCID; }
			set
			{
				this.OnPropertyValueChange(_.CCID,_CCID,value);
				this._CCID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IFCheck
		{
			get{ return _IFCheck; }
			set
			{
				this.OnPropertyValueChange(_.IFCheck,_IFCheck,value);
				this._IFCheck=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string InPlan
		{
			get{ return _InPlan; }
			set
			{
				this.OnPropertyValueChange(_.InPlan,_InPlan,value);
				this._InPlan=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IFCheckBY
		{
			get{ return _IFCheckBY; }
			set
			{
				this.OnPropertyValueChange(_.IFCheckBY,_IFCheckBY,value);
				this._IFCheckBY=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? ExamNum
		{
			get{ return _ExamNum; }
			set
			{
				this.OnPropertyValueChange(_.ExamNum,_ExamNum,value);
				this._ExamNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Csort
		{
			get{ return _Csort; }
			set
			{
				this.OnPropertyValueChange(_.Csort,_Csort,value);
				this._Csort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Mark
		{
			get{ return _Mark; }
			set
			{
				this.OnPropertyValueChange(_.Mark,_Mark,value);
				this._Mark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sortname
		{
			get{ return _Sortname; }
			set
			{
				this.OnPropertyValueChange(_.Sortname,_Sortname,value);
				this._Sortname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string byState
		{
			get{ return _byState; }
			set
			{
				this.OnPropertyValueChange(_.byState,_byState,value);
				this._byState=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PlanSort
		{
			get{ return _PlanSort; }
			set
			{
				this.OnPropertyValueChange(_.PlanSort,_PlanSort,value);
				this._PlanSort=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? EXRID
		{
			get{ return _EXRID; }
			set
			{
				this.OnPropertyValueChange(_.EXRID,_EXRID,value);
				this._EXRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public Guid? GUID
		{
			get{ return _GUID; }
			set
			{
				this.OnPropertyValueChange(_.GUID,_GUID,value);
				this._GUID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TermName
		{
			get{ return _TermName; }
			set
			{
				this.OnPropertyValueChange(_.TermName,_TermName,value);
				this._TermName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Exp
		{
			get{ return _Exp; }
			set
			{
				this.OnPropertyValueChange(_.Exp,_Exp,value);
				this._Exp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Direct
		{
			get{ return _Direct; }
			set
			{
				this.OnPropertyValueChange(_.Direct,_Direct,value);
				this._Direct=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ctype
		{
			get{ return _ctype; }
			set
			{
				this.OnPropertyValueChange(_.ctype,_ctype,value);
				this._ctype=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 考试类型
		{
			get{ return _考试类型; }
			set
			{
				this.OnPropertyValueChange(_.考试类型,_考试类型,value);
				this._考试类型=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? SelectDate
		{
			get{ return _SelectDate; }
			set
			{
				this.OnPropertyValueChange(_.SelectDate,_SelectDate,value);
				this._SelectDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CCIDB
		{
			get{ return _CCIDB; }
			set
			{
				this.OnPropertyValueChange(_.CCIDB,_CCIDB,value);
				this._CCIDB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NeedPJ
		{
			get{ return _NeedPJ; }
			set
			{
				this.OnPropertyValueChange(_.NeedPJ,_NeedPJ,value);
				this._NeedPJ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string inSplan
		{
			get{ return _inSplan; }
			set
			{
				this.OnPropertyValueChange(_.inSplan,_inSplan,value);
				this._inSplan=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SplanMemo
		{
			get{ return _SplanMemo; }
			set
			{
				this.OnPropertyValueChange(_.SplanMemo,_SplanMemo,value);
				this._SplanMemo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MarkA
		{
			get{ return _MarkA; }
			set
			{
				this.OnPropertyValueChange(_.MarkA,_MarkA,value);
				this._MarkA=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Cunit
		{
			get{ return _Cunit; }
			set
			{
				this.OnPropertyValueChange(_.Cunit,_Cunit,value);
				this._Cunit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Period
		{
			get{ return _Period; }
			set
			{
				this.OnPropertyValueChange(_.Period,_Period,value);
				this._Period=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.学绩分,
				_.绩点,
				_.备注,
				_.成绩,
				_.Exam,
				_.Normal,
				_.实验,
				_.TrueResult,
				_.TruePoint,
				_.ECID,
				_.EPID,
				_.CLID,
				_.SPID,
				_.SRID,
				_.StuID,
				_.State,
				_.TCID,
				_.Discipline,
				_.学号,
				_.系部,
				_.班级,
				_.学生姓名,
				_.教学班级名称,
				_.课程名称,
				_.CCnameEng,
				_.学分,
				_.任课教师,
				_.当前学期,
				_.ATYID,
				_.Minor,
				_.SequID,
				_.DeptID,
				_.GradeID,
				_.CLassID,
				_.DeptCode,
				_.PSID,
				_.ReportState,
				_.IFOK,
				_.Lev,
				_.Oper,
				_.TotalNum,
				_.IsMain,
				_.ATNo,
				_.MState,
				_.PJState,
				_.CCode,
				_.Grid,
				_.PayMoneyState,
				_.stdstate,
				_.GRName,
				_.TMID,
				_.CCID,
				_.IFCheck,
				_.InPlan,
				_.IFCheckBY,
				_.ExamNum,
				_.Csort,
				_.Mark,
				_.Sortname,
				_.byState,
				_.PlanSort,
				_.EXRID,
				_.GUID,
				_.TermName,
				_.Exp,
				_.Direct,
				_.ctype,
				_.考试类型,
				_.SelectDate,
				_.CCIDB,
				_.NeedPJ,
				_.inSplan,
				_.SplanMemo,
				_.MarkA,
				_.Cunit,
				_.Period};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._学绩分,
				this._绩点,
				this._备注,
				this._成绩,
				this._Exam,
				this._Normal,
				this._实验,
				this._TrueResult,
				this._TruePoint,
				this._ECID,
				this._EPID,
				this._CLID,
				this._SPID,
				this._SRID,
				this._StuID,
				this._State,
				this._TCID,
				this._Discipline,
				this._学号,
				this._系部,
				this._班级,
				this._学生姓名,
				this._教学班级名称,
				this._课程名称,
				this._CCnameEng,
				this._学分,
				this._任课教师,
				this._当前学期,
				this._ATYID,
				this._Minor,
				this._SequID,
				this._DeptID,
				this._GradeID,
				this._CLassID,
				this._DeptCode,
				this._PSID,
				this._ReportState,
				this._IFOK,
				this._Lev,
				this._Oper,
				this._TotalNum,
				this._IsMain,
				this._ATNo,
				this._MState,
				this._PJState,
				this._CCode,
				this._Grid,
				this._PayMoneyState,
				this._stdstate,
				this._GRName,
				this._TMID,
				this._CCID,
				this._IFCheck,
				this._InPlan,
				this._IFCheckBY,
				this._ExamNum,
				this._Csort,
				this._Mark,
				this._Sortname,
				this._byState,
				this._PlanSort,
				this._EXRID,
				this._GUID,
				this._TermName,
				this._Exp,
				this._Direct,
				this._ctype,
				this._考试类型,
				this._SelectDate,
				this._CCIDB,
				this._NeedPJ,
				this._inSplan,
				this._SplanMemo,
				this._MarkA,
				this._Cunit,
				this._Period};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_StuReport");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学绩分 = new Field("学绩分","vw_StuReport","学绩分");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 绩点 = new Field("绩点","vw_StuReport","绩点");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 备注 = new Field("备注","vw_StuReport","备注");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 成绩 = new Field("成绩","vw_StuReport","成绩");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Exam = new Field("Exam","vw_StuReport","Exam");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Normal = new Field("Normal","vw_StuReport","Normal");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 实验 = new Field("实验","vw_StuReport","实验");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrueResult = new Field("TrueResult","vw_StuReport","TrueResult");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TruePoint = new Field("TruePoint","vw_StuReport","TruePoint");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ECID = new Field("ECID","vw_StuReport","ECID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EPID = new Field("EPID","vw_StuReport","EPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLID = new Field("CLID","vw_StuReport","CLID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPID = new Field("SPID","vw_StuReport","SPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SRID = new Field("SRID","vw_StuReport","SRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StuID = new Field("StuID","vw_StuReport","StuID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","vw_StuReport","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TCID = new Field("TCID","vw_StuReport","TCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Discipline = new Field("Discipline","vw_StuReport","Discipline");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学号 = new Field("学号","vw_StuReport","学号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 系部 = new Field("系部","vw_StuReport","系部");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 班级 = new Field("班级","vw_StuReport","班级");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学生姓名 = new Field("学生姓名","vw_StuReport","学生姓名");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 教学班级名称 = new Field("教学班级名称","vw_StuReport","教学班级名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 课程名称 = new Field("课程名称","vw_StuReport","课程名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCnameEng = new Field("CCnameEng","vw_StuReport","CCnameEng");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学分 = new Field("学分","vw_StuReport","学分");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 任课教师 = new Field("任课教师","vw_StuReport","任课教师");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 当前学期 = new Field("当前学期","vw_StuReport","当前学期");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATYID = new Field("ATYID","vw_StuReport","ATYID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Minor = new Field("Minor","vw_StuReport","Minor");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SequID = new Field("SequID","vw_StuReport","SequID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptID = new Field("DeptID","vw_StuReport","DeptID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GradeID = new Field("GradeID","vw_StuReport","GradeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CLassID = new Field("CLassID","vw_StuReport","CLassID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","vw_StuReport","DeptCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PSID = new Field("PSID","vw_StuReport","PSID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReportState = new Field("ReportState","vw_StuReport","ReportState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IFOK = new Field("IFOK","vw_StuReport","IFOK");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Lev = new Field("Lev","vw_StuReport","Lev");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Oper = new Field("Oper","vw_StuReport","Oper");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TotalNum = new Field("TotalNum","vw_StuReport","TotalNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsMain = new Field("IsMain","vw_StuReport","IsMain");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATNo = new Field("ATNo","vw_StuReport","ATNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MState = new Field("MState","vw_StuReport","MState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PJState = new Field("PJState","vw_StuReport","PJState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCode = new Field("CCode","vw_StuReport","CCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Grid = new Field("Grid","vw_StuReport","Grid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PayMoneyState = new Field("PayMoneyState","vw_StuReport","PayMoneyState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field stdstate = new Field("stdstate","vw_StuReport","stdstate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GRName = new Field("GRName","vw_StuReport","GRName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TMID = new Field("TMID","vw_StuReport","TMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCID = new Field("CCID","vw_StuReport","CCID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IFCheck = new Field("IFCheck","vw_StuReport","IFCheck");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field InPlan = new Field("InPlan","vw_StuReport","InPlan");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IFCheckBY = new Field("IFCheckBY","vw_StuReport","IFCheckBY");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExamNum = new Field("ExamNum","vw_StuReport","ExamNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Csort = new Field("Csort","vw_StuReport","Csort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Mark = new Field("Mark","vw_StuReport","Mark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sortname = new Field("Sortname","vw_StuReport","Sortname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field byState = new Field("byState","vw_StuReport","byState");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanSort = new Field("PlanSort","vw_StuReport","PlanSort");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EXRID = new Field("EXRID","vw_StuReport","EXRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GUID = new Field("GUID","vw_StuReport","GUID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TermName = new Field("TermName","vw_StuReport","TermName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Exp = new Field("Exp","vw_StuReport","Exp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Direct = new Field("Direct","vw_StuReport","Direct");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ctype = new Field("ctype","vw_StuReport","ctype");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 考试类型 = new Field("考试类型","vw_StuReport","考试类型");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SelectDate = new Field("SelectDate","vw_StuReport","SelectDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCIDB = new Field("CCIDB","vw_StuReport","CCIDB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NeedPJ = new Field("NeedPJ","vw_StuReport","NeedPJ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field inSplan = new Field("inSplan","vw_StuReport","inSplan");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SplanMemo = new Field("SplanMemo","vw_StuReport","SplanMemo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MarkA = new Field("MarkA","vw_StuReport","MarkA");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Cunit = new Field("Cunit","vw_StuReport","Cunit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Period = new Field("Period","vw_StuReport","Period");
		}
		#endregion


	}
}

