//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace IeidjtuKCB.Model
{

	/// <summary>
	/// 实体类vw_UserInDept 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_UserInDept")]
	[Serializable]
	public partial class vw_UserInDept : Entity 
	{
		#region Model
		private string _UName;
		private string _Account;
		private string _password;
		private string _DeptCode;
		private string _Question;
		private DateTime? _LastDate;
		private string _Oper;
		private string _DeptName;
		private int _UDPID;
		private string _RoleName;
		private int? _Role;
		/// <summary>
		/// 
		/// </summary>
		public string UName
		{
			get{ return _UName; }
			set
			{
				this.OnPropertyValueChange(_.UName,_UName,value);
				this._UName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Account
		{
			get{ return _Account; }
			set
			{
				this.OnPropertyValueChange(_.Account,_Account,value);
				this._Account=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string password
		{
			get{ return _password; }
			set
			{
				this.OnPropertyValueChange(_.password,_password,value);
				this._password=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange(_.DeptCode,_DeptCode,value);
				this._DeptCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Question
		{
			get{ return _Question; }
			set
			{
				this.OnPropertyValueChange(_.Question,_Question,value);
				this._Question=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Oper
		{
			get{ return _Oper; }
			set
			{
				this.OnPropertyValueChange(_.Oper,_Oper,value);
				this._Oper=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange(_.DeptName,_DeptName,value);
				this._DeptName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int UDPID
		{
			get{ return _UDPID; }
			set
			{
				this.OnPropertyValueChange(_.UDPID,_UDPID,value);
				this._UDPID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RoleName
		{
			get{ return _RoleName; }
			set
			{
				this.OnPropertyValueChange(_.RoleName,_RoleName,value);
				this._RoleName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Role
		{
			get{ return _Role; }
			set
			{
				this.OnPropertyValueChange(_.Role,_Role,value);
				this._Role=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.UName,
				_.Account,
				_.password,
				_.DeptCode,
				_.Question,
				_.LastDate,
				_.Oper,
				_.DeptName,
				_.UDPID,
				_.RoleName,
				_.Role};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._UName,
				this._Account,
				this._password,
				this._DeptCode,
				this._Question,
				this._LastDate,
				this._Oper,
				this._DeptName,
				this._UDPID,
				this._RoleName,
				this._Role};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_UserInDept");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UName = new Field("UName","vw_UserInDept","UName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Account = new Field("Account","vw_UserInDept","Account");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field password = new Field("password","vw_UserInDept","password");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode","vw_UserInDept","DeptCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Question = new Field("Question","vw_UserInDept","Question");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","vw_UserInDept","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Oper = new Field("Oper","vw_UserInDept","Oper");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName","vw_UserInDept","DeptName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UDPID = new Field("UDPID","vw_UserInDept","UDPID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleName = new Field("RoleName","vw_UserInDept","RoleName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Role = new Field("Role","vw_UserInDept","Role");
		}
		#endregion


	}
}

